### ISSUE TITLE
Agent Based Modeling and FBA

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#100]
Hi,
I am trying to understand where agent based modeling is depicted in the code of BacArena. Similarly, it is not clear to me where in the code FBA takes place, as optimizeProb occurs many times in many files.

**Comment by maringos** [comment]
By the way! Happy Anniversary Wishes for the 100th issue!

**Comment by jotech** [comment]
Hi and congratulations to the anniversary ;o) 
Agent-based modeling is more a modeling concept then a specific line of code. For a general, short introduction I would refer to John Hollands article on [complex adaptive systems](http://tonyrivera.net/wp-content/uploads/2013/12/Complex-Adaptive-Systems.pdf). As you may see it is more the class structure of BacArena which is in line with this paradigm. In addition to class deisgn, the iterative behavior (updating of environment and agents) is done by the beloved function ``simEnv()``.  
For the second question, FBA (and similar things like MTF) is performed when ever ``optimizeProb`` is called ;) But the main growth model is done by ``growth()`` and ``cellgrowth()``.

Perhaps the class diagram can illustrate this a little bit more:
![class](https://user-images.githubusercontent.com/573461/35622151-1a90183e-0687-11e8-8ded-e9349c14e161.png)

**Comment by maringos** [comment]
Thanks for the answer which was very helpful. As far as I know cells can move in the Arena and also chemotaxis is provided by the program. Are they aspects of Agent Based Modeling?

**Comment by euba** [comment]
Hi,

Happy anniversary from me too :)
Sorry that I was so quite lately.

I would say that all concepts are agent based modeling. To make it simple, agent based modeling is basically some rules that act on agents in a spatio-temporal environment. FBA is just another rule that acts on the agents (e.g., microbes).  Therefore, FBA and ABM are not clearly separated, but integrated.
The FBA always runs to calculate the growth of the agents.

Cheers, Eugen

**Comment by jotech** [comment]
@euba quiet or quite ;D

**Comment by jotech** [comment]
@maringos I would recommend to have at least a short read into John Holland because he is one the pioneers in the agent based field and explains the concept of ``agents`` and ``rules`` _quite_ good!

**Comment by euba** [comment]
@jotech quiet ;)
@maringos and yes, John Holland is _quite_ good!

**Comment by maringos** [comment]
@euba & @jotech I have read it! It is amazing and inspiring when someone reads about concepts without numbers, p-values etc....Thanks for the suggestion!
