### ISSUE TITLE
One Organism with Two Phenotypes

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#103]
Dear All,
If someone decides to set `maxweight=Inf` for a bacterium, then the organism cannot duplicate. This is correct. If you check, `sim@phenotypes` may one or two values. 

Of course this is not correct, unless we are talking about the god Janus who has two faces.

My code (run it at least three times and check in each run):
```
sybil::SYBIL_SETTINGS("SOLVER","glpkAPI")
library(BacArena)
arena <- Arena()
data(Ec_core)
x<-Ec_core
bac_wild <- BacArena::Bac(model=x, speed = 0,
                          maxweight=Inf, growtype='linear') 
arena <- BacArena::addOrg(arena, bac_wild, amount=1)
arena <- BacArena::addSubs(object = arena,smax = 1)
sim <- BacArena::simEnv(arena, time=10)
sim@phenotypes
```

**Comment by euba** [comment]
Hi,
The reason for this is that per organism there is a default phenotype stored, which is independent of the BacArena simulation and based on a simple FBA of the metabolic model without any constraints.
We thought it makes sense to keep it as a reference if you want to compare what the organism is able to produce without any media contraints.
Cheers, euba

**Comment by maringos** [comment]
Many thanks for your answer. I understand your comments but, unfortunately, it is not clear to me which phenotype I should use from the following in order to construct my argument - idea based on the results.
```

sim@phenotypes
      ecoli_core_model       ecoli_core_model 
"12111120022122212211" "12111120002122212211" 
```

**Comment by euba** [comment]
Well, it depends on what you want to do. I would take the second one, because this is the phenotype that occured during the BacArena simulations. The first one is just one FBA on the unconstrained model.

**Comment by maringos** [comment]
Nice! Should I also imagine that if I use a secondary objective I may find three or more phenotypes?

**Comment by euba** [comment]
By the way: It is also possible for one cell to get multiple phenotypes during the simulation steps, or to get the same phenotype as the unconstrained model. Imagine the following: A cell takes up a preferred carbon source, but then the carbon source is gone and the cell has to take up another carbon source from the environment.
So it could be that you are getting more than two phenotypes if you look at all simulation steps.

**Comment by maringos** [comment]
OK!  I will check out. By now I should close the issue.
