### ISSUE TITLE
Chemotaxis

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#105]
Hi,
I am trying to simulate chemotaxis but I am not sure how....
The following example returns error:
```
library(BacArena)
data(Ec_core)
bac2 <- Bac(model=Ec_core, chem = "EX_co2(e)")
arena <- Arena(n=10, m=10)
arena <- addOrg(arena, bac2, amount=2)
arena <- addDefaultMed(object = arena,org = bac2)
sim <- simEnv(object = arena,time = 4)
```

Error in x[[jj]][iseq] <- vjj : replacement has length zero

**Comment by maringos** [comment]
I would propose that this line is problematic : `j `should not be there https://github.com/euba/BacArena/blob/a16ea2741f788e912935a925442d906ae96f933d/R/Organism.R#L886

Anyway, my question still remains: How to simulate chemotaxis....

**Comment by euba** [comment]
Hi, Check if it works now with the new commit https://github.com/euba/BacArena/commit/4b78b2eeabad6ffdc66984243cd032c2e8946573
For some reason the position is sometimes returned as NULL.

**Comment by maringos** [comment]
Now a new error occurs:
```
Error in chemotaxis(object, arena, j) : 
  trying to get slot "diffmat" from an object of a basic class ("NULL") with no slots
```

**Comment by maringos** [comment]
No this new problem occurs when the compound of chemotaxis is not correct! Thanks! Any guide to simulate chemotaxis....

**Comment by jotech** [comment]
Hm but the compound is missing, right?
I updated the example bcb90b4b9c3b8fd91288c9669daf07eb05536666
```R
bac <- Bac(Ec_core,deathrate=0.05, chem = "EX_o2(e)",
            minweight=0.05,growtype="exponential") #initialize a bacterium
arena <- Arena(n=20,m=20) #initialize the environment
arena <- addOrg(arena,bac,amount=10) #add 10 organisms
arena <- addSubs(arena,40) #add all possible substances
chemotaxis(bac,arena,1, "EX_glc(e)")
```
I also tried your example and got no problem at all. Please check and close if it is solved.
