### ISSUE TITLE
No uptake for reaction

### ISSUE THREAD

**Issue by fairquestion** [euba/BacArena#107]
Dear all,

When working with the sybil's Ecoli core model I have tried to modify this model by introducing a test reaction:

"EX_no2(e)"	"no2 exchange"	"[e] : no2 <==> "	"Reversible"	"C_e"	-10	1000	0	""	"Exchange"
"no2t"	"no2 transporter via diffusion"	"no2[e] --> no2[c]"	"Irreversible"	"C_c, C_e"	0	1000	0	"s0001"	"Transport, Extracellular"
"13tv"	"testreaction"	"[c] : no2 --> no3"	"Irreversible"	"C_c"	0	1000	0	""	"energy"
"no3t"	"no3 transporter via diffusion"	"no3[c] --> no3[e]"	"Irreversible"	"C_c, C_e"	0	1000	0	"s0001"	"Transport, Extracellular"
"EX_no3(e)"	"no3 exchange"	"[e] : no3 <==> "	"Reversible"	"C_e"	0	1000	0	""	"Exchange"

As you can see it just takes no2, converts it into no3 and releases it again. However no uptake is detected (there is growth cell and everything like in the normal core model). Do you have any idea? 
no2 and no3 have been added to metabolites file and no errors where detected when running BacArena.

Thanks.

**Comment by euba** [comment]
Hi,

Most likely it is not used by the model. You could simulate the model with sybil's `optimizeProb` to see if there is flux through the reactions.
If you want to force the usage of these reactions, I guess you could also enforce secretion of no3 by changing the lower bound of EX_no3 to a positive value.

Best, Eugen

**Comment by fairquestion** [comment]
Hi Eugen, 

Thanks, will check it and give you an answer.

Best,
Fair
