### ISSUE TITLE
SIHUMI tsv files (sybilSBML removed from CRAN)

### ISSUE THREAD

**Issue by fairquestion** [euba/BacArena#108]
Dear all,

sybilSBML has been removed from CRAN : https://cran.r-project.org/web/packages/sybilSBML/index.html however is it still possible to load tsv model to work with BacArena (In my case I can not install sybilSBML) .

I would like to ask you if it is possible to get the tsv models for the SIHUMI community showd in your paper. Would like to perform some test. Or if you know any script to convert SBML to tsv . 

Best and thanks,
Fair.

**Comment by maringos** [comment]
Hi Fair,
I would suggest to check this [zip file](https://doi.org/10.1371/journal.pcbi.1005544.s006) published as supplement of the BacArena [article](https://doi.org/10.1371/journal.pcbi.1005544). It contains SIHUMI models, although I do not know if they can help you, as you wrote about the tsv format.
Kind Regards,
George

**Comment by fairquestion** [comment]
Hi George,
Thanks. Sybil requires models in tsv format (SBtab) to be loaded (like the e.coli core model provided by sybil), since sybilSBML has been removed from CRAN, would be great to have access to those model in a readable format . Do you know if it is possible to save this RData file as tsv (SBtab)? 

Best and thanks,
Fair

**Comment by euba** [comment]
Hi,

Since the sybil models are already stored as a RData file, you don't need to convert or load it in a different format. 

Best, Eugen

**Comment by fairquestion** [comment]
Hi all,

Just as clarification, I am just trying to reproduce your results and play a little bit with the SIHUMI community, change reaction paramenters, etc.

I have loaded the RData file and when I write "sihumi" it gives me the list of models (8 in total). However in order to work with it, sybil needs an object of class modelorg . To get this object and according to the manual it requires a tsv or SBML file, for example I can use the readTSVmod command and load any model in tsv format.

Do you know how can I load your Rdata file in order to be recognized as an object of class modelorg?

Thanks,
Fair

**Comment by euba** [comment]
Hi,

'sihumi' is already a list of modelorg objects. Check these commands:
`lapply(sihumi,class)`
`class(sihumi[[1]])`

Best, Eugen

**Comment by euba** [comment]
Hi,

The 'sihumi' models were originally based on the AGORA SBML version published on VMH, but since the publication of BacArena, the AGORA models have changed continuously. Most of these changes are addition of some reactions (in particular reactions involved in bile acid metabolism). I would check the older version published on VMH.

Best, Eugen

**Comment by fairquestion** [comment]
Hi!

Just as information for future users, the Rdata models can be converted to the sybil tsv format with the next command (for example for the second model):

modelorg2tsv(upgradeModelorg(sihumi[[2]]), prefix="test") 

Best,
Fair.
