### ISSUE TITLE
You passed a nil value!

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#113]
Dear All,
 
I am experiencing the following issue: For my reasons I want to create arena, add the models and then save it. After loading it back in the environment later, and I possibly add compounds, I start the simulation and I immediately I am getting a strange error:
_glpkAPI::getColsLowBndsGLPK(lp@oobj, j) : 
  You passed a nil value!_

Any possible reasons?
Regards,
George

**Comment by utkinaira** [comment]
Hi @maringos ,

Suddenly, I am getting the same error. Before that happened simulation was running fine, I didn't change absolutely anything.
Do you remember how did you fix this problem?

Thanks,
Irina

**Comment by jotech** [comment]
could you provide an example for this?

**Comment by jotech** [comment]
please reopen if still relevant

**Comment by mTangherlini** [comment]
Dear all,
As of today (03/06/2021) I am experiencing this issue for the first time. I just installed all the required packages, but nothing seems to work. I'm on a Windows 10 laptop, using RStudio 1.4 with R 4.0.5.

**Comment by jotech** [comment]
hi, could you provide some more details here? I'm wondering what exactly does not work?

**Comment by mTangherlini** [comment]
> hi, could you provide some more details here? I'm wondering what exactly does not work?

Hello,
The issue is raised when I create an Arena, add a bunch of models with a default medium based on one of them and then start the simulation. As soon as the calculation starts, I get the error 
```
glpkAPI::getColsLowBndsGLPK(lp@oobj, j) :
You passed a nil value!
```
I even tried it on a Centos 7-based workstation with R v4  and RStudio, and I keep getting the same error. However, some months ago on my older Windows 10-based laptop it worked just fine with the same models, the same arena and the same simulation settings.

**Comment by silvtal** [comment]
Looks like a R v4 problem... I have the same problem in Ubuntu 21.10 with R 4.1.1.

**Comment by jotech** [comment]
strange I don't have issues with R>=4 if somebody can provide a minimal example I'm happy to have a look at it :)

**Comment by silvtal** [comment]
My problem is actually with parallelization, I can run non-parallelized simulations just fine. So it's not urgent for me. But here's an example (R version 4.1.1)

```
library(BacArena)
library(parallel)

data("Ec_core")
Ec <- Bac(Ec_core, type="ecoli_wt")

replicates <- 4
cores <- ifelse(detectCores() >= 2,4,1)
cl <- makeCluster(cores, type="PSOCK")

clusterExport(cl, c("Ec"))
simlist <- parLapply(cl, 1:replicates, function(i){
  arena <- BacArena::Arena (n=50, m=50)
  arena <- BacArena::addOrg(arena, Ec, amount=10)
  arena <- BacArena::addSubs(arena, smax=5, mediac="EX_glc(e)", unit="mM")
  arena <- BacArena::addSubs(arena, smax=1, mediac=c("EX_pi(e)", "EX_h2o(e)", "EX_o2(e)", "EX_nh4(e)"), unit="mM")
  sim <- BacArena::simEnv(arena, time=10, sec_obj='mtf')
})
```

```
Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: You passed a nil value!
```

Thank you so much for your time !!

**Comment by jotech** [comment]
Hi @silvtal 
sorry for the late reply I just got back to it! The problem with your code is that the ``Bac`` object is created outside the parallelization. It is shared via ``clusterExport`` but the object also contains a pointer to the optimization object which needs to be unique for each run

**Comment by silvtal** [comment]
I see! Thank you so much 😊

**Comment by jotech** [comment]
perfect if it works for you now :) the vignette is also updated to inform about this potential issue!
