### ISSUE TITLE
mtf and minimal growth

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#119]
Dear All,

I am facing the following issue: My model shows growth 1e-06 and when the code is in the line for applying mtf, the simulation does not continue. Obviously, the solver cannot find any solution. Adjusting the cutoff to 1e-05 solves the problem but is it optimal practice?

Kind Regards
George

**Comment by jotech** [comment]
I would say yes because solutions <=1e-6 are rounded to zero. The accuracy of the solution is not as good in case of small numbers. That is why we integrated the cutoff

**Comment by maringos** [comment]
Thanks  :) GM
