### ISSUE TITLE
libglpk-dev for non-debian RPM systems

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#127]
Hi All,

I was wondering if there is anything equivalent to libglpk-dev for Linux systems that use RPM?

Kind Regards,
@maringos

**Comment by jotech** [comment]
do you mind using google :P 
should be glpk-devel on redhat systems

**Comment by maringos** [comment]
I will try to reproduce the error and I will come back...

**Comment by jotech** [comment]
so far you didn't tell anything about an error?

**Comment by maringos** [comment]
I cannot reproduce anymore the error while installing `BacArena` in Fedora (after `glpk-devel `being installed) anymore. Thanks for the info.
