### ISSUE TITLE
Undefined error with fluxes of simulation object

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#128]
Dear All,

I am experiencing a very strange issue, which is not consistent - if I rerun the simulation, it is gone.
I have a setting where the same bacterial model is used but as three different organisms (e.g. type="Α",type="B", type="C"). After simulation I want to find all the related fluxes of each type by this code (part of a function)

```
#find model's index
        S <- unique(grep(pattern = "A", x = names(sim@specs),
                         ignore.case = T, invert = F, value = T))
        ggj <- as.vector(sapply((sim@mflux)[S], attributes))
#extract model's fluxes in the simulation
        a3 <- BacArena::plotReaActivity(simlist = sim, reactions = ggj[[1]],
                                        ret_data = T)
```
Sometimes I get the error
```
Error in BacArena::plotReaActivity(simlist = sim, reactions = ggj[[1]],  : 
  You have to define reactions
```
which means that the object ggj does not have any entries. What is more strange, if I search for fluxes of the rest of the organisms, there are fluxes of the type "A", so there is no reason why ggj returns no reactions.

I understand that this issue is very vaguely described and I promise to come back when I have something more concrete.

I look forward to your ideas.

Kind Regards,
Georgios

**Comment by maringos** [comment]
Just to visualize my previous issue

![screenshot_2018-11-08_15-33-37](https://user-images.githubusercontent.com/17548206/48205031-b1df3000-e36b-11e8-816f-fbf95b267064.png)



I look forward to your ideas.

Kind Regards,
Georgios

**Comment by maringos** [comment]
update: One way to bypass this issue is to replace the `ggj` object with
`ggj <- as.vector(sim@specs[[S]]@model@react_id)`

GM

**Comment by jotech** [comment]
is this still happening?

**Comment by maringos** [comment]
It is ages since I have worked with the script, since I hacked it using this [solution](https://github.com/euba/BacArena/issues/128#issuecomment-437056819). We should not assume that problem is gone.

**Comment by jotech** [comment]
please reopen if still relevant
