### ISSUE TITLE
Testing supplementary R script to reproduce _P. aeruginose_ biofilm simulation on Linux system

### ISSUE THREAD

**Issue by zhssakura** [euba/BacArena#129]
Hi all,
We I was testing supplementary R script 'S2_journal.pcbi.1005544.s005.R' (# Script to reproduce _P. aeruginose_ biofilm simulation. File S1 is needed (contains metabolic model and diet)) on Linux system, I got the following results. I think this is not what is expected to be. Could you please help me to improve or fix it? Thank you very much

`Rscript /srv/scratch/z5095298/sponge_modoling/BacArena/S2_journal.pcbi.1005544.s005.R &`

```
# [1] 23822
# (base) [z5095298@kc05b01 BacArena]$ Loading required package: sybil
# Loading required package: Matrix
# Loading required package: lattice
# Loading required package: ReacTran
# Loading required package: rootSolve
# Loading required package: deSolve
# Loading required package: shape
# BacArena paper: https://doi.org/10.1371/journal.pcbi.1005544
#  Tutorial: https://CRAN.R-project.org/package=BacArena/vignettes/BacArena-Introduction.pdf
#  Development and help: https://github.com/euba/bacarena
# Error in checkForRemoteErrors(val) : 
#   10 nodes produced errors; first error: No biomass reaction found in model.
# Calls: print ... clusterApply -> staticClusterApply -> checkForRemoteErrors
# Timing stopped at: 0.004 0.002 2.331
# Execution halted
```

**Comment by jotech** [comment]
Hi, thanks for your feedback :) We changed the code to detect biomass reactions automatically but there seemed to be an issue with this. I tried to fix it could you please update to the latest version and try again?
```r
library(devtools)
install_github(repo="euba/bacarena", quick=TRUE)
```

**Comment by zhssakura** [comment]
Hi @jotech 

Thanks for your reply. What I am trying is updating the 'BacArena' package to the latest version by using the one in your GitHub. 

So, I am trying to install the package of 'devtools' on my Mac and HPC account. It has been successfully installed on my laptop, but it seems harder for the HPC account, so it is currently under the help of our IT service. 

I did not change anything in the R script 'S2_journal.pcbi.1005544.s005' and 'S4_journal.pcbi.1005544.s007'. Running these two scripts seems to require a lot of sources (S4 has been running for over 20h and still not finished, is this the same case for all users?). So I prefer to do that on our HPC rather than my laptop. 

I will let you know how it goes after the updates. So please do not close this issue.

Thank you very much!

Shan

**Comment by jotech** [comment]
Hi @zhssakura, I'm sorry that installation is causing problems! Strange that ``devtools`` is not working out of the box. I created a R package from the current tree by myself [BacArena_1.7.tar.gz](https://github.com/euba/BacArena/files/2562223/BacArena_1.7.tar.gz). Maybe you want to try this one instead? 
```R
R CMD INSTALL BacArena_1.7.tar.gz
```
The scripts take some time because several replicates are computed, too. For **file S4**, the script is even simulating all scenarios from the publication.

In case you just want to try, you can fasten it a bit:
```R
library(BacArena)
library(parallel)

cl <- makeCluster(5, type="PSOCK",outfile="cluster_sihumi.log")

diet = read.csv("TableS1.csv",header=T) #read in diet information
load("FileS2.RData") #read in metabolic models as R list "sihumi" with models

clusterExport(cl, "sihumi") #export models to clusters
clusterExport(cl, "diet") #export diet to clusters

print(system.time(simlist_mucus <- parLapply(cl, 1:5, function(i){ # **only 5 replicates**
  sybil::SYBIL_SETTINGS("SOLVER","cplexAPI") #set solver to CPLEX
  arena <- BacArena::Arena(50, 50, stir=F, Lx=0.025, Ly=0.025, tstep=1) # **smaller arena**
  for(i in 1:length(sihumi)){ #add metabolic models as bacteria to the environment
    model = sihumi[[i]]
    bac = BacArena::Bac(model=model, growtype="exponential", speed=10)
    arena = BacArena::addOrg(arena, bac, amount=50) # **less inital bacs)
  }
  diet = diet[which(diet$Exchange %in% arena@mediac),] #ensure that all diet components can be used by the models
  muc = as.character(diet$Exchange[which(diet$category=="mucin")]) #create a vector with only mucus glycans
  arena = BacArena::addSubs(arena, smax=diet$concentration.im.mM,difspeed=diet$diffconstant,unit="mM",
                            mediac=as.character(diet$Exchange)) #add metabolites to environment
  arena = BacArena::createGradient(arena,smax=1e-03,mediac=muc,position='left',steep=0.5,add=T,unit="mM") #add a mucus gradient
  sim = BacArena::simEnv(arena, time=6) # **simulate for only 6h**
}) ))
stopCluster(cl)
```
This will create a smaller arena with less inital bacteria and simulate only one scenario for 6 hours.
This should also run quite fine on a desktop computer! Let me know if it's convenient for you :)

**Comment by zhssakura** [comment]
Hi @jotech ,

Thank you very much. I am trying both scripts on the HPC now. 
After the original R script of S4 finished with the report as follows:
`
Job Name:   qsub_BacArenaNew_R351_S4.sh
Exec host:  kc08b16/5+kc08b16/4+kc08b16/3+kc08b16/2+kc08b16/1+kc08b16/0
Execution terminated
Exit_status=0
resources_used.cput=43:16:19
resources_used.mem=55332388kb
resources_used.vmem=56581580kb
resources_used.walltime=08:45:31`
`
It generates an output 'cluster_sihumi.log' and I have pasted the last few lines as follows. Does that mean it has finished successfully?

`
iteration-end: 16 	 organisms: 8522 	 biomass: 6981.92 pg 

                                                   count   biomass           %
Anaerostipes_caccae_DSM_14662                        831  712.3665 0.053020158
Bacteroides_thetaiotaomicron_VPI_5482               3004 2431.7016 0.002204865
Bifidobacterium_longum_NCC2705                       761  651.7152 0.002106445
Blautia_producta_DSM_2950                            780  633.9517 0.049895251
Clostridium_ramosum_VPI_0427_DSM_1402                415  340.2667 0.053344756
Escherichia_coli_str_K_12_substr_MG1655             2325 1877.1904 3.360222930
Lactobacillus_plantarum_subsp_plantarum_ATCC_14917   406  334.7279 0.052994940

	time total:  2247.741 	diffusion:  132.915  ( 5.9 %)
--------------------------------------------------------------------Warning messages:
1: In BacArena::simEnv(arena, time = 16) :
  If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
2: In BacArena::simEnv(arena, time = 16) :
  If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
Warning messages:
Warning messages:
Warning messages:
1: Warning messages:
1: 1: In BacArena::simEnv(arena, time = 16) :1: In BacArena::simEnv(arena, time = 16) :In BacArena::simEnv(arena, time = 16) :
 In BacArena::simEnv(arena, time = 16) :
  If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
2: In BacArena::simEnv(arena, time = 16) :
  If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').

 
  If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
 If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
 If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
2: In BacArena::simEnv(arena, time = 16) :
  If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
2: In BacArena::simEnv(arena, time = 16) :
  If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
2: In BacArena::simEnv(arena, time = 16) :
  If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
starting worker pid=20219 on localhost:11886 at 22:26:44.786
starting worker pid=20228 on localhost:11886 at 22:26:45.009
starting worker pid=20237 on localhost:11886 at 22:26:45.215
starting worker pid=20246 on localhost:11886 at 22:26:45.420
starting worker pid=20255 on localhost:11886 at 22:26:45.626
Loading required package: cplexAPI
Loading required package: cplexAPI
Loading required package: cplexAPI
Loading required package: cplexAPI
Loading required package: cplexAPI`

Reguards,

Shan

**Comment by jotech** [comment]
yes it seems to have worked :) The warning is because I excluded the ``mtf`` (minimize total flux) optimization which takes more time but is recommended (more reliable fluxes). You should be able to start the analysis with the results by e.g. ``plotGrowthCurve(sim)``.
In case you want to redo the simulation with mtf enabled, just use: ``sim = BacArena::simEnv(arena, time=6, sec_obj='mtf')``.

**Comment by zhssakura** [comment]
Hi @jotech ,

Thank you very much. It runs much faster with the script you provided and I would love to test for the next step. If you like I will let you know how it goes. :)

Regards.

Shan

**Comment by jotech** [comment]
yeah sure let me know how it works :)
