### ISSUE TITLE
Syntrophic two-species community model

### ISSUE THREAD

**Issue by fairquestion** [euba/BacArena#132]
Dear all,

In your paper is written:
_Syntrophic two-species community model Manual curated genome-scale metabolic models were retrieved for the hydrogen producing bacterium Clostridium beijerinckii [35] and the methanogenic archaeon Methanosarcina barkeri [36]._ 

But the simulation was not uploaded. Is it possible to get the simulation, the models and the nutrients .csv file like with SIHUMI? I would really apreciate it. 

Best and thanks,
Fair

**Comment by euba** [comment]
Hi,

The analysis details are in the method section of the paper in "Syntrophic two-species community model".
Here is the the script to perform the simulations:

```
library(BacArena)
library(sybil)
library(sybilSBML)
library(ggplot2)

barkeri <- readSBMLmod("barkeri_mod.xml")
beijerinckii <- readSBMLmod("beijerinckii_mod.xml")

sybil::SYBIL_SETTINGS("SOLVER","cplexAPI") #set solver to CPLEX
arena <- Arena(100, 100, stir=F, Lx=0.025, Ly=0.025, tstep=0.3)
bac1 <- Bac(model=barkeri)
bac2 <- Bac(model=beijerinckii)
arena <- addOrg(arena, bac1, amount=1,x=60,y=50,biomass=1)
arena <- addOrg(arena, bac2, amount=1,x=40,y=50,biomass=1)
minmed = c("EX_4abz(e)","EX_cobalt2(e)","EX_nac(e)","EX_h2o(e)","EX_h(e)","EX_nh4(e)","EX_ni2(e)","EX_pi(e)","EX_so3(e)","EX_cys_L(e)","EX_so4(e)")
arena <- addSubs(arena, smax=0, unit="mmol/cell")
arena <- addSubs(arena, mediac=minmed, smax=1, unit="mmol/cell")
arena <- addSubs(arena, mediac="EX_glc_D(e)", smax=1, unit="mmol/cell")
arena <- addSubs(arena, mediac="EX_co2(e)", smax=1, unit="mmol/cell")
arena <- addSubs(arena, mediac="EX_h2(e)", smax=1e-10, unit="mmol/cell")
sim=simEnv(arena, time=24)
```
Here are also the sbml model files:
[beijerinckii_barkeri_mod.zip](https://github.com/euba/BacArena/files/2654114/beijerinckii_barkeri_mod.zip)


Best, Eugen

**Comment by fairquestion** [comment]
Hi Eugen,

Thanks a lot. Are these attached models already modified like the paper states?, otherwise I can modify it myself.

**Comment by fairquestion** [comment]
Super :D , it is working properly. Excellent material for my research. Maybe you can add it to the examples, It is an easy to follow and understandable 2 organism interaction arena, SIHUMI is way much more complex to decipher what is going on there.

**Comment by euba** [comment]
Great! Thanks for the suggestion, we will consider including it in the next version of the vignette.
