### ISSUE TITLE
modelseed to BIGG db

### ISSUE THREAD

**Issue by fairquestion** [euba/BacArena#133]
Dear all,

I have two nicely curated models with this kind of metabolite names: EX_cpd00011(e), EX_cpd00418(e)...

Is there any way to convert it to your BIGGdb names? A table with the translations would be ideal.

Best and thanks,
Fair

**Comment by euba** [comment]
Hi,

check out the VMH website here: https://www.vmh.life/files/reconstructions/Recon/SEED2VMH_translation.csv
to download a translation table.

As an alternative, I would recommend MetaNetX: https://www.metanetx.org/mnxdoc/mnxref.html

Best, Eugen

**Comment by fairquestion** [comment]
Hi Eugen,

Just to let you know, this file: https://www.vmh.life/files/reconstructions/Recon/SEED2VMH_translation.csv 

is empty, 0 kb

**Comment by euba** [comment]
Hi,

thanks for noticing, I contacted the people behind VMH and they uploaded a fixed table, so the link should work now (in case it's still not working, reload your cache).

Best, Eugen
