### ISSUE TITLE
Relative amount of substance

### ISSUE THREAD

**Issue by thh32** [euba/BacArena#134]
I know the reverse of this issue was submitted years ago, however I was wondering if you retained a method to visulaise the relative change in substance abundance.

Currently it is clear that something is limiting the growth of my models, however it is likely a substance which started in low abundance and so does not appear on the "Strongly changing substances" graph. 

Is it possible to get a similar graph but for this with the largest relative changes?

Thanks,
Tom

**Comment by jotech** [comment]
Maybe you can iterate on all substances and have a look manually:
```R
data(sihumi_test)
getSubHist(sihumi_test, sub="EX_but(e)")
```
You said that you are looking for a limiting compound. Have you tried the shadow costs? They are especially implemented to check for substances which could increase growth.
``plotShadowCost(sihumi_test, spec_nr=7)[[2]]``
In this example ``spec_nr`` is the number of the organism according to ``names(sihumi_test@specs)``.
Let me know if this helps you around.

**Comment by jotech** [comment]
please reopen if still relevant
