### ISSUE TITLE
kill individuals

### ISSUE THREAD

**Issue by fairquestion** [euba/BacArena#136]
Dear all,

Is it possible to kill individuals in the simulation? with the consequent release of substances. I would like to simulate viral lysis but I can not find specific commands for such purpose. 

Best,
Fair.

**Comment by euba** [comment]
Hi,

Yeah, I think we don't have a function for specific individual death yet as far as I know. There is lysis option for `Bac` option though:
```
bac <- Bac(model, lysis=T)
```
With this the metabolites according the biomass definition are secreted in the medium, when the organism dies.

Cheers, Eugen

**Comment by jotech** [comment]
I'm just thinking about how this could be implemented in principle. How is your simulations realized? Do you have a viral model for this? What is the event that triggers the death of individuals?

**Comment by fairquestion** [comment]
Hi all, 

BacArena is very useful to simulate the effects of disturbance in a medium. One of the main disturbance factors according to several hypothesis is the viral lysis, at least in marine environments. 

What I want to simulate is viral disturbance, lets show a toy example with bacteria a and b:

time1: one bacteria is infected by chance by a virus specialized only on b bacteria, in this case, the bald b represents the infected bacteria.

aabaaa
ab**b**bbaa
aabaab

time2: bald b dies, and if adjacent b are present, they also got infected. Since the virus is not specialized on a, a bacteria are not infected. Obviously the contents of the bacteria are released thanks to the lysis function, feeding other bacteria.

aa**b**aaa
a**b** **b**baa
aa**b**aab

Time 3: in the end, only bacteria b on the botton right corner survives thanks to a different spatial distribution.

aa aaa
a   **b**aa
aa aab


I can made a simple script to simulate the viral behaviours, just by stopping the simulation, modifying it and re-run it again, but It would be ideal to have an already implemented killing function to kill targets on demand while releasing its contents to the media.

If you are interested we can also make a small collab to test it in different in silico communities. 

Best,
Fair.

**Comment by utkinaira** [comment]
Dear all,

I have a similar question: is there a way to remove some individuals (say, random part of the grid) from arena after each iteration? This might help to simulate community in microbiota more realistically because some part of lumen-associated microbiota just flows away (i.e., appears in the end in feces) and doesn't interact with the rest of community as well as frees up space on the grid.

Thanks in advance!

**Comment by jotech** [comment]
hi @fairquestion and @utkinaira 
sorry took me some time to come up with a first solution for this.
I added a matrix (``arean@removeM``) where you can specify coordinates from which organisms are deleted in each iterations.
I think for your scenario @fairquestion it is not sufficient yet but maybe both of you can give it a try and we will try to improve it further?
Let me know what you think about it!

```r
library(BacArena)
data("Ec_core")
bac <- Bac(Ec_core)
arena <- Arena(n=20, m=20)
arena <- addOrg(arena,bac,amount=20)
arena <- addSubs(arena, smax=0.005, mediac="EX_glc(e)", unit="mM")
arena <- addSubs(arena, smax=1, mediac=c("EX_pi(e)", "EX_h2o(e)",
                                         "EX_o2(e)", "EX_nh4(e)"), unit="mM") 
arena@removeM[c(1,20),1:20] <- 1
arena@removeM[1:20,c(1,20)] <- 1
image(arena@removeM)
sim   <- simEnv(arena, time=5)
```

**Comment by utkinaira** [comment]
Hi @jotech, thank you so much!

I have a question regarding the update of BacArena (in order to see introduced changes like @removeM). Probably, I'm doing something wrong - I just re-install the package with ```install_github("euba/bacarena")```, but still do not see the added slot "removeM" (```Error: no slot of name "removeM" for this object of class "Arena"```). What is the correct way to update the package?

I am wondering whether this code would be suitable for random killing of some portion of organisms on the grid or I misunderstood something and it will kill much more than I need:
``` 
# for example, I want to remove 10% of organisms every 2 iterations, so within the loop I do:
sim <- simEnv(arena, time=2)
arena2 <- getArena(sim,2)
neworgdat <- arena2@orgdat #get the current orgdat
neworgdat <- neworgdat[-sample(nrow(neworgdat), round(nrow(neworgdat) / 10)), ] #remove ~10% of individuals randomly 
arena2 <- changeOrg(arena2,neworgdat)
```

Thank you in advance!

**Comment by jotech** [comment]
hi @utkinaira,
hm this is really strange.. It works over here and I tried another machine right now. Just to be sure, did you reloaded the package after updating? (restart R or ``detach("package:BacArena", unload=TRUE)`` before ``library(BacArena)``?
Yes, your codes looks fine :)
If you want so, you could also change ``orgdat`` directly:
```r
sim <- simEnv(arena, time=2)
arena2 <- getArena(sim,2)
arena2@orgdat <- arena2@orgdat[-sample(nrow(arena2@orgdat), round(nrow(arena2@orgdat) / 10)), ] #remove ~10% of individuals randomly 
simEnv(arena2, time=2)
```

**Comment by utkinaira** [comment]
Oh yeah, this ```detach("package:BacArena", unload=TRUE)``` helped! 
Thank you @jotech  :)

**Comment by fairquestion** [comment]
wow thanks, I am going to test it.

**Comment by euba** [comment]
Hi @fairquestion,

You can check out the structure of orgdat:
```
head(arena2@orgdat)
```
There is a `x` and `y` column, which specify the position of each individual in each row. If you want for example to remove half of the individuals in one half of the environment you can do this:
```
arena2@orgdat <- arena2@orgdat[-which(arena2@orgdat$x<arena2@n/2),]
```
or you can also remove an individual in one specific position by specifying `x` and `y` coordinates.

Best, Eugen

**Comment by jotech** [comment]
there is a new feature in bacarena which integrates simple predator-prey dynamics!

```R
library(BacArena)
data("Ec_core")

pred  <- Bac(Ec_core, type="predator")
prey  <- Bac(Ec_core, type="prey", predator="predator")
arena <- Arena(n=50, m=50)
arena <- addOrg(arena,prey,amount=100)
arena <- addOrg(arena,pred,amount=25)
arena <- addSubs(arena, smax=0.005, mediac="EX_glc(e)", unit="mM")
arena <- addSubs(arena, smax=1, mediac=c("EX_pi(e)", "EX_h2o(e)",
                                         "EX_o2(e)", "EX_nh4(e)"), unit="mM") 

sim   <- simEnv(arena, time=20, with_shadow = T, sec_obj = F)
plotGrowthCurve(sim)[[1]]
```
![image](https://user-images.githubusercontent.com/573461/57456805-8f709580-726e-11e9-9d80-40b3adf76bea.png)

**Comment by utkinaira** [comment]
Looks nice! Thank you!

**Comment by jotech** [comment]
please reopen if still relevant
