### ISSUE TITLE
plotReactActivity units across plots

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#139]
Dear All,

I have noticed that there is discrepancy in units among the heat-map and plots of the plotReaActivity function. The values of heatmap seem to be ten times more than in the other plots.

Kind Regards,
@maringos 
![heat-map](https://user-images.githubusercontent.com/17548206/53092535-4df50780-3515-11e9-8b9a-cfd97b468df7.jpeg)
![plot1](https://user-images.githubusercontent.com/17548206/53092536-4df50780-3515-11e9-988c-d7fe6c324ce2.jpeg)
![plot2](https://user-images.githubusercontent.com/17548206/53092538-4df50780-3515-11e9-812d-d28298e40298.jpeg)

**Comment by jotech** [comment]
can't reproduce can you give an example for this?

**Comment by jotech** [comment]
please reopen if still relevant
