### ISSUE TITLE
Programming and BacArena

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#140]
Dear All,

I am writing to you concerning the code structure of _BacArena_. Specifically, if someone reads the [vignette](https://cran.r-project.org/web/packages/BacArena/vignettes/BacArena-Introduction.pdf), she/he can straightforward start working with _BacArena_ and its objects/functions.
Let us imagine that we have constructed a very complex _BacArena_ (with many different models, arena with occupied areas, parallelization, stops and starts of simulation to manipulate the arena etc.).
Would it make sense to make an new class so that it contains all the above characteristics or is it just enough to run the functions of  _BacArena_  directly (e.g. `simEnv` function) to get the needed objects (e.g. `Arena` or  `Eval `object)?
I look forward to your opinion and I thank you beforehand.

Kind Regards,
Georgios

**Comment by jotech** [comment]
depends I would say. if you use the same setup in a lot of cases under different conditions an own class which inherits from bacarena's main classes maybe makes sense in terms of less duplicated code and readability

**Comment by jotech** [comment]
please reopen if still relevant
