### ISSUE TITLE
fluxVarSim and rnd argument

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#141]
Dear All,

I am writing regarding to the `fluxVarSim` function. I was wondering why you created the specific argument `rnd`. I understand that `rnd` is associated to the rounding of the return values, but the dangers or oppurtunities that may arise from changing this argument are not clear to me.

Kind Regards,
Georgios Marinos

**Comment by euba** [comment]
Hi,

The idea behind this is to round flux values that are close to zero and most likely represent numerical inaccuracies or are not large enough to be relevant for the simulation. In `simEnv` we also have a similar idea with the `cutoff` parameter.

Cheers, Eugen

**Comment by maringos** [comment]
Thanks :)
