### ISSUE TITLE
Setting environmental concentrations in simulations

### ISSUE THREAD

**Issue by ziels** [euba/BacArena#142]
I am wondering if there is a way run simulations with inputted time-series vectors of environmental parameter concentrations? For instance, I would like to set the oxygen level initially at 0 mg/L, and then increase it to 2 mg/L at time=30 min. Thanks!

**Comment by jotech** [comment]
Besides using a rather tricky differential equations with boundary conditions, I think the easiest and shortest way would be to simulate, stop, add additional substances and continue simulation:

```R
library(BacArena)
data("Ec_core")

bac  <- Bac(Ec_core)
arena <- Arena(n=20, m=20, tstep=0.5) # setting time step to half an hour
arena <- addOrg(arena,bac,amount=20)
arena <- addSubs(arena, smax=0.05, mediac="EX_glc(e)", unit="mM")
arena <- addSubs(arena, smax=1, mediac=c("EX_pi(e)", "EX_h2o(e)",
                                         "EX_nh4(e)"), unit="mM") 
sim   <- simEnv(arena, time=4, with_shadow = T)

sim <- addSubs(sim, smax=0.05, mediac="EX_o2(e)", unit="mM")
sim   <- simEnv(sim, time=8, with_shadow = T)

plotGrowthCurve(sim)
plotSubCurve(sim, c("EX_glc(e)", "EX_o2(e)", "EX_for(e)", "EX_ac(e)"))[[2]]
``` 

You can see how oxygen level increases and fermentation stops and continues when oxygen is depleted again:

![example](https://user-images.githubusercontent.com/573461/55889057-c0e33c00-5bb0-11e9-9738-6e70e3af9f85.png)

**Comment by jotech** [comment]
added also a short tutorial
https://gist.github.com/jotech/cd6c073ee99856b2ad0742aad9b8a31c

**Comment by ziels** [comment]
That is really awesome, thanks for the tutorial! 

Is it possible to 'fix' environmental parameters at a given concentration? For instance, could oxygen be set at 2 ppm and held there (even while the microbes were consuming it)? In reality, this would occur with an O2 supply and controller. To simulate this, would we need to adjust diffusion into the Arena? 

Thanks again!

**Comment by euba** [comment]
In principle you could use the solution from @jotech and just add your concentration after simulating just one iteration step:
```
arena <- addSubs(arena, smax=0.05, mediac="EX_o2(e)", unit="mM", add=F)
sim   <- simEnv(arena, time=1)
for(i in 1:10){#put in here how many time steps you want
  sim <- addSubs(sim, smax=0.05, mediac="EX_o2(e)", unit="mM", add=F)
  sim   <- simEnv(sim, time=1)
}
plotSubCurve(sim, c("EX_glc(e)", "EX_o2(e)", "EX_for(e)", "EX_ac(e)"))[[2]]
```
Another quick and dirty solution is to add an extremely high oxygen concentration from the beginning in case you just want unlimited oxygen:
```
arena <- addSubs(arena, smax=10000000000, mediac="EX_o2(e)", unit="mM")
```

**Comment by ziels** [comment]
I'll give that a try, thanks!
