### ISSUE TITLE
Minor typo found

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#144]
Hi
I have found a typo in the warning message...
```
Warning message:
In simEnv(arena, time = 5) :
  If growth is limitted by maximum weight for an organism (max_weight=TRUE) it is recommended to use minimize total flux (sec_obj='mtf').
```
limitted - > limited

**Comment by jotech** [comment]
thanks @maringos !
i changed it will online with the next bigger commit :)

**Comment by maringos** [comment]
corrected with commit https://github.com/euba/BacArena/commit/e2209fa903f94b7fe5f057326a189f4062b456cb
