### ISSUE TITLE
Cross-feeding plot customization

### ISSUE THREAD

**Issue by tenguzame** [euba/BacArena#145]
Greetings,
I'm exploring your interesting piece of software, and I'm finding it quite useful for my own line of research. I'm writing to ask whether there's a chance to give users the capability for customizing the igraphs produced by the FindFeeding modules. In some cases it seems that I'm looking at some kind of yarn ball, and it's hard to discern the feeding pathways among the organisms in my simulations.
Best regards

**Comment by euba** [comment]
Hi,

If you use `findFeeding3` you also export a data.frame (it's the first element of the returned list) with all the relevant information so that you can make your own igraph plot:
```
library(BacArena)
library(igraph)

data("sihumi_test")
ff3 = findFeeding3(sihumi_test, time=5, mets=c("EX_lac_D(e)","EX_etoh(e)"))
ffdata = ff3[[1]]
```
Then you can reformat the data and plot with igraph:
```
g <- graph.data.frame(ffdata[,1:2], directed=TRUE)
plot(g)
```
Hope this helps.

Best, Eugen

**Comment by jotech** [comment]
please reopen if still relevant
