### ISSUE TITLE
Seeking advice for modeling eukaryotic cells 

### ISSUE THREAD

**Issue by utkinaira** [euba/BacArena#149]
Hi all!

I am wondering if it would be a valid approach to try tissue modeling with BacArena in the following way: add Human-class organisms representing each cell type in tissue to the arena and simulate same way as a bacterial community. 
I have single-cell RNAseq data (bronchial airways epithelial tissue) so I know which cell types are there and I can use this data to constrain the bronchial tissue model to get models for different cell types. My main concerns are 
1) biomass reaction as an objective (these aren't tumor cells); 
2) how to keep a realistic spatial organization when the community of cells will be growing if I don't set the growth rate to 0 (for example by selecting maxweight = Inf?) )

Please let me know what you think.

Thanks,
Irina

**Comment by jotech** [comment]
Hi Irina,
you have a very valid point and unfortunately also a complicated one.
The use of biomass optimization for multi-cellular organisms is far less valid then for microbes. Three things come into my mind:
- think about other simple objectives (e.g. ATP maintenance)
- check the transcriptomic data and literature for phenotypes common in bronchial tissue and create a tissue-specific objective (for example: short chain fatty acid consumption for gut cells)
- you can try to use the transcriptomic data directly (see: [http://dx.doi.org/10.1186/1752-0509-6-73](http://dx.doi.org/10.1186/1752-0509-6-73) for further hints)

For the spatial organization, I would recommend to use the occupyM matrix of ``arena`` to separate human and bacterial cells. This will hinder bacteria to overgrow the human tissue and you can set the growth rate to zero. Interactions by metabolite exchange will be still possible!

Hope my remarks are at least a bit helpful.
best wishes, johannes

**Comment by utkinaira** [comment]
Hi Johannes,

Thank you very much for your reply and suggestions! I will try maybe select more simple objective as a secondary objective (secObj parameter) together with a zero growth rate and see how it goes.

occupyM matrix is a good solution indeed, totally forgot about that, thanks!

Best,
Irina

**Comment by jotech** [comment]
please reopen if still relevant
