### ISSUE TITLE
Explanation of warnings

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#151]
Dear All,

I would like to ask you to remind me of what the following warnings mean. I remember @jotech has explained them in person, but I cannot recall.
```
"Median lower bound for non-zero and non-Inf exchanges is:06"
Warning message:
In Organism(model = model, ...) :
  Many lower bounds of of the model seems to be set to non -infinity. Please be aware that they will be used as maximal uptake rates even when the available medium is more abundant! (set setAllExInf=TRUE to reset all exchanges to -INF)

```
Regards,
Georgios

**Comment by hites77** [comment]
I am getting the same issue for one of my genome model

**Comment by jotech** [comment]
https://github.com/jotech/gapseq/issues/43

**Comment by jotech** [comment]
the default behavior was changed to ``setAllExInf=TRUE`` from now on. The warning should not be occur anymore. For a discussion of the background please refer to https://github.com/jotech/gapseq/issues/43

also reopen issue if things are still unclear
