### ISSUE TITLE
Installing BacArena on Windows 10

### ISSUE THREAD

**Issue by mTangherlini** [euba/BacArena#155]
Hello! I'm trying to install BacArena on my Windows 10-based laptop to carry out some tests, but I can't seem to be able to do it. The installer halts when trying to install the glpkAPI library, which looks for "glpk.h" but can't find it:
`*** arch - i386
C:/RBuildTools/3.4/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.2/include" -DNDEBUG -g -D_R_=1 -DUSE_R=1 -I/include -DCHECK_GLPK_ARGS    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c glpkAPI.c -o glpkAPI.o
In file included from glpkAPI.h:26:0,
                 from glpkAPI.c:27:
glpkR.h:27:18: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
                  ^
compilation terminated.
make: *** [glpkAPI.o] Error 1`
I tried to manually install and compile the glpk library for Windows, which seemed to complete, but I can't tell R where to look for the headers it requires... what can I do?
Best regards

**Comment by euba** [comment]
Hi,

You can check the install help of the glpk API R package: https://cran.r-project.org/web/packages/glpkAPI/INSTALL
Here is the section for the windows installation:
# ---------------------------------------------------------------------------- #
# Windows installation
# ---------------------------------------------------------------------------- #

For the installation on Windows systems the file Makewars.win in src/ is
required. The file looks like this:

PKG_CPPFLAGS=-g -D_R_=1 -DUSE_R=1 -I${GLPK_HOME}/include -DCHECK_GLPK_ARGS
PKG_LIBS=-L${GLPK_HOME}/lib -lglpk -lgmp

with the environment variable GLPK_HOME being the installation directory
of GLPK and GNU BIGNUM.


You need to add your installation directory in a file within src/

Cheers, Eugen

**Comment by mTangherlini** [comment]
Thanks for the comment! I managed to successfully install glpkAPI and BacArena, but I still need help for sybilSBML. I'm currently working on an x64 environment on a 64-bit laptop, but R still tries to compile the 32-bit version of the tool, which raises compilation errors due to the lack of the related libSBML libraries.
I was thinking of two possible solutions: 1) forcing R not to install the 32-bit version or 2) trying to set environment variables pointing at both versions of libSBML. Since I wasn't able to find ways to implement option #1, I tried to work out option #2, but I still get errors from Rtools which can't find the proper libraries... how can I do it?
Best regards

**Comment by euba** [comment]
Hi,

The sybilSBML package is a little bit challenging to install. The most important thing is to have the correct version of libSBML. My guess is that you might have two versions of libSBML (32- and 64bit) installed.
You can check out the sybilSBML help: http://www2.uaem.mx/r-mirror/web/packages/sybilSBML/vignettes/sybilSBML.pdf
they actually recommend to install rsbml prior from bioconductor.

You can also check out the `readMATmod("model.mat")` function in case you want to import matlab models.

Cheers, Eugen

**Comment by mTangherlini** [comment]
Wohoo! Great, I managed to install it!
Thanks a lot! Now I can start working. I had to move on this laptop because somehow I couldn't install it on my main Centos-based workstation. This means any analyses will take somewhat longer, but at least it will do it.
Thanks again!

**Comment by euba** [comment]
That's great news. Have fun with the simulations!
