### ISSUE TITLE
Do entries of lobnd have names?

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#159]
Hi,

I was reviewing the functionality of the argument `setAllExInf`.
Could you recheck if the line below is correct? `lobnd` entries do not seem to have names. On the other hand, why do we need this part: `names(lobnd) %in% medc `

https://github.com/euba/BacArena/blob/98952a9a1a202dfd288525d953ef07e7d295d549/R/Organism.R#L184

Regards,
Georgios

**Comment by jotech** [comment]
I don't think so, just check two lines before:
https://github.com/euba/BacArena/blob/98952a9a1a202dfd288525d953ef07e7d295d549/R/Organism.R#L182
``medc`` are exchange reactions which could be user-defined in some cases and thus differ from ``sybil::findExchReact``.

**Comment by maringos** [comment]
Now, I get it! Thanks :)
