### ISSUE TITLE
Change default value ex="EX_" in Organism constructor

### ISSUE THREAD

**Issue by jotech** [euba/BacArena#16]
Shouldn't the constructor of class `Organism` use ex=NA in default case so that `sybil` could be used to search exchange reactions?

**Comment by euba** [comment]
Hi, sybil tries to find exchange reactions according to the stoichiometric matrix by looking which reactions produce a metabolite out of nothing, so it outputs also demand reactions and in the end we need to look for a string anyway.

**Comment by jotech** [comment]
Nice, so you are keen to answer even the old ones ;)
Question is whether the sybil approach or the string approach is more suitable?
But since we are using only bigg/vhm default nomenclature at the moment, it is perfect as it is.
In general, I would say things would be more suitable using the sybil approach in the default mode.

**Comment by euba** [comment]
Better late then never ;-)
The problem with the sybil approach is really the demand reactions, we definitely don't want to treat them as exchange reactions. Maybe we can use the sybil approach and then check which strings are over-represented in the output? You would expect that most reaction found by sybil are exchange reactions and have a common substring that identifies them as exchanges (e.g. "EX_").

**Comment by maringos** [comment]
Hello everybody! I do not know how relevant is my comment~so be prepared accordingly:
Should we add substances without the ex_...(e) format? For example I am using the the [ IEC1907](http://wwwde.uni.lu/lcsb/research/mol_systems_physiology/in_silico_models) model that has two extracellular compartments. When I am adding the substance, I should think where to add what (i.e. to use e or u compartment)? Also when I am looking for the levels of the substances in the arena, I have to sum the two compartments....I understand that these compartments should not be mixed, but in case we want, this problem arises.
