### ISSUE TITLE
plotReaActivity breaks in sims with many replications

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#164]
Hi,

I am trying to analyse a 7h simulation with 10 replications by utilising plotReaActivity, but I get an error 
`Error in object@mfluxlist[[i]] : subscript out of bounds`

It seems that the plot tries to find data that do not exist.....

I am wondering if this line is associated with this issue:
https://github.com/euba/BacArena/blob/c0b3b11bb9067f77fa5334cdfce0964c753b4e05/R/Stuff.R#L866

Should it not be  `names(object@mfluxlist[[t]][[spec]]` ?

Regards,
Georgios

PS: Indeed if I do  `sim <- sim[1:7]`, it works!

**Comment by jotech** [comment]
you are right! thank you :)
