### ISSUE TITLE
Rtools for standard BacArena

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#176]
Hi, 

I want to share my experience with installing _BacArena_ from scratch in Windows. I have noticed that there is a warning that Rtools are missing when one installs _BacArena_ (without _Rtools_ beforehand). However, _BacArena_ works after the installation. Is this a normal behaviour?

Best Regards,
George

**Comment by jotech** [comment]
as far as I know rtools is need for packages that need to be compiled when binaries are not available which could depend on os and r version

**Comment by maringos** [comment]
OK thanks for the reply, I will close this issue.

**Comment by hites77** [comment]
Is BacArena not available for R 4.2.0 ?

**Comment by jotech** [comment]
hi @hites77 
it should! At least it is working for me on R 4.3.

Have you tried installing it via devtools::install_github("euba/bacarena")?

**Comment by hites77** [comment]
installation failed 
error:

Removed empty directory 'BacArena/examples'
   Removed empty directory 'BacArena/model'
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       'BacArena/data/sihumi_test.rda'
       
Warning message in i.p(...):
"installation of package '[//.../BacArena_1.8.2.tar.gz)' had non-zero exit status"

**Comment by hites77** [comment]
installed BacArena after installing sybil using this method
install.packages("remotes")
remotes::install_github("SysBioChalmers/sybil")

thanks

**Comment by jotech** [comment]
Many thanks for providing more details!

I'm curious about which R version you are using because the dependency is on R> =3.5, and you mentioned that you are working with R 4.2. If this is the case, there shouldn't be a problem. Could you please double-check?
After all, these are only warnings, could you load the packages?
