### ISSUE TITLE
Model grows without any carbon source

### ISSUE THREAD

**Issue by Zhelunnn** [euba/BacArena#178]
Hi,

Thank you for developing this. I used my model obtained from gapseq fill to run Bacarena. I just got a weird issue that my model can grow without Carbon and it can not grow with only water or other inorganic until I added Fe2+ into my medium. This never happen in other model. 

Could you help me with this? I uploaded the model from gapseq, from Bacarena and medium in my github in case you need to check out. https://github.com/Zhelunnn/Bacarene_issues

Best,
Zhelun

**Comment by jotech** [comment]
Hi @Zhelunnn 
interesting example! I think the problem comes by a certain reaction you seem to have added to the model
```R
library(sybil)
mod <- readRDS("model_obtained_from_gapseq.RDS")
printReaction(mod, react="rxn40961_zhelun5")

abbreviation	equation
rxn40961_zhelun5	(2) cpd00067[c0] + (1) cpd00081[c0] --> (3) cpd00001[c0] + (1) cpd00004[c0] + (1) cpd00003[c0] + (1) cpd00239[c0] + (2) cpd11606[c0] + (2) cpd11451[c0]
rxn40961_zhelun5	(2) H+-c0 + (1) Sulfite-c0 --> (3) H2O-c0 + (1) NADH-c0 + (1) NAD-c0 + (1) H2S-c0 + (2) Menaquinone 7-c0 + (2) mql7-c0 99.75
```
This reaction is not mass balanced. It is producing nad and menaquinone out of sulfite, causing a total mass imbalance of
`C:226, H:317, N:14, O:36, P:4`. 
I think this is causing a free lunch, and the model can grow! 

Correcting the reaction side of the reduced/oxidized nad and menaquinone should fix it, shouldn't it?

**Comment by Zhelunnn** [comment]
How exciting! I have checked each equation but the reactions I added. That's a really terrible mistake. 
Thank you so much for this.

**Comment by jotech** [comment]
you are welcome!
I was wondering if this reaction is of general interest and is currently missing in gapseq we could also think about adding it to the gapseq reaction database. What do you think?

**Comment by Zhelunnn** [comment]
It couldn't be better! If you can add reactions about Sulfur metabolism such as dissimilatory sulfur reduction, thiosulfate oxidation and sulfur reduction in gapseq database, I would be very grateful. These reactions are generally important in marine microbes.

**Comment by jotech** [comment]
Okay then, let's have a try :) I opened an issue for it at jotech/gapseq#131 
If you don't mind, could you please provide details on the missing functionality?

**Comment by Zhelunnn** [comment]
Of course. I would try to do it, but I have to admit that the formula of some compounds were annotated 'null' in 'seed_metabolite_edited.tsv', which is hard to judge whether I should use the reactions involved with these compounds. So although I need these reactions, I still put them aside. 

Fortunately, a large proportion of these compounds are carrier in a complete pathway and what I can do at this stage is to rewrite a new 'all-in-one' reaction which ignores the involvement of carrier to replace the original one (just like 'rxn40961_zhelun' we talked above). 

So I can not guarantee its reliability, this way may only be useful for my case. That's because you need to think of the completeness of pathways. Please let me know how do you think of it.

**Comment by jotech** [comment]
I see! Let's move the discussion to https://github.com/jotech/gapseq/issues/131, and could you provide the (metacyc?) pathways that are missing or not working correctly from your experience?
