### ISSUE TITLE
Metabolite diffusion

### ISSUE THREAD

**Issue by zhssakura** [euba/BacArena#179]
Dear authors,

I have a question about how would the metabolite diffusion work in BacArena. This would help me to understand the metabolic interactions between bacteria. For example, at the end of one hour, would the substance emitted by a single microbial cell diffuse throughout the radius of the circle which it exists, or would the substance occupy the entire gride cell occupied by the microbe? How would it be at the end of the 2nd cycle?

Here, I provided a plot to clarify my question: I’ve modified the grid cell length (Lx and Ly = 0.2 cm) and metabolite diffusion rate (difspeed = 3.14E-02 cm^2/h). 
Would the diffusion look like the top scenario or the bottom scenario? Thank you!
![image](https://user-images.githubusercontent.com/27931331/188788208-cd5a8e44-2b75-430e-84ed-808a0f6df18f.png)
Kind regards,

Shan

**Comment by jotech** [comment]
hi,
the grid cells are discrete units and have single concentration
values attached to them. So if the diffusion reaches another grid cell
the complete grid cell is having the corresponding concentration.
If I understood you correctly this should correspond to the bottom
scenario in the figure you send.

You could also try to explore it a bit further, for example:
```R
library(BacArena)
data(sihumi_test)
image(matrix(sihumi_test@medlist[[2]]$`EX_co2(e)`,nrow=sihumi_test@n))
```
This should provide you with an image of the concentrations of co2 in
the second time step of the example data.

**Comment by zhssakura** [comment]
Hi @jotech,

So in my case, it does not matter how large the single grid cell is, or what the community density is, as long as the substrate diffusion rate is fixed. Thank you very much for the interpretation. It is very helpful.

Best wishes,

Shan
