### ISSUE TITLE
rmSubs(arena, mediac) doesn't work

### ISSUE THREAD

**Issue by joyvgeerestein** [euba/BacArena#190]
Hi! 

When trying to delete specifc subtances out of the default medium, whilst maintaining the rest, I encounter an error.
When I call arena, I do in fact see that the substances have been removed, however when I simulate eval <- simEnv(arena,time=x) (x being the time), I still get growth based on the initial default medium including the subtances I thought I deleted. 

Any ideas?

**Comment by jotech** [comment]
hi @joyvgeerestein 
I could try to help! May I ask, how you have removed the substances?

**Comment by joyvgeerestein** [comment]
Hi! 
arena <- Arena(n=20, m=20)
arena <- addOrg(arena,bac,amount=20)

# Add default medium
arena <- addDefaultMed(arena,bac,unit="fmol/cell") (I changed the unit because otherwise it would be too high concentration and I wouldn't see the differences) 

# Delete all carbohydrates out of medium 
mediac <- c("EX_cpd00314_e0", "EX_cpd00588_e0", "EX_cpd00306_e0", "EX_cpd00208_e0", "EX_cpd00179_e0", "EX_cpd00076_e0", "EX_cpd00082_e0", "EX_cpd00108_e0", "EX_cpd00027_e0")
rmSubs(arena, mediac)

arena (when I call arena here I do in fact see the susbtances removed)

#simulate x hours of growth
eval <- simEnv(arena,time=10)

But after simulation they are still incorporated in the arena. Any ideas? 

Besides, also wondering what would be best for me to do for arena size and amount of organism, as well as time to run it; I am working with a model of Megasphaera, a novel strain, and trying to compute its possible stickland metabolism and how that affects its growth, by adapting AA and sugar availability in the medium.  What would you suggest for arena size, initial amount, and/or time to run? 

Thanks!

**Comment by jotech** [comment]
> arena (when I call arena here I do in fact see the susbtances removed)

I'm not sure, it should be
```R
arena <- rmSubs(arena, mediac)
```
Could you give it a try?

**Comment by joyvgeerestein** [comment]
Yes works like that, thank you!

**Comment by jotech** [comment]
I'm glad that it helped! :)
