### ISSUE TITLE
Reoccuring Error Message

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#25]
When I use plot commands, this error appears without any other consistent clue: 
Error: Faceting variables must have at least one value

**Comment by jotech** [comment]
This occurs probably in cases where the feature used for arrange the subplots is static or has no varying values.
Could you please be more specific, what kind of functions did you use?

**Comment by maringos** [comment]
plotSubUsage has often this error

**Comment by euba** [comment]
Hi, I could reproduce the error in plotSubUsage. I think the problem occurs when none of the substances that should be plottet are used by the community (e.g. have no flux). So basically, the data.frame that contains the usage info is empty and then ggplot2 returns the error. I now added a warning that also outputs this information. 
Are there any other functions that output this error?

**Comment by maringos** [comment]
For now, I cannot reproduce this error for other plots. Actually the problem as stated above exists, possible due to the fact that there has been no updated BacArena version so far. 
PS: I am using the latest version and I prefer this way to update my BacArena: 

> library(devtools)
> install_github(repo = "euba/BacArena")

**Comment by maringos** [comment]
PlotSubUsage error has not been fixed yet. Any news?

**Comment by jotech** [comment]
Unfortunately, it's not easy to fix without example.
Best case would be if you construct a _minimal_ example with the default models:
```
data(package="BacArena")
```
So there are: ecoli, poa2,sihumi_test. With a working example everybody can reproduce your problem and a fix will be easier to deploy.
Nonetheless, I tried to get something around. Please have a try.

**Comment by maringos** [comment]
In my view, it was much easier to use the example of the BacArena Readme (adapted). Please check the input and  the output below:

```
> library(BacArena)
> data("Ec_core")
> arena <-  Arena (n=20, m=20)
> arena <-  addOrg(object = arena,specI = bac,amount = 5)
> arena <-  addDefaultMed(object = arena,org = bac)
> arena <-  addSubs(object = arena,smax = 0,add = F,mediac = "EX_ac(e)")
> sim<-arena
> sim<-simEnv(object = sim,time = 5,verbose = FALSE)
> plotSubUsage(sim,"EX_ac(e)")
[[1]]

[[2]]

> plotSpecActivity(sim, "EX_ac(e)")
[[1]]

[[2]]

```
![plotsubusage1](https://cloud.githubusercontent.com/assets/17548206/21184385/91e124e8-c20c-11e6-8398-ce29933672b9.jpeg)
![plotsubusage2](https://cloud.githubusercontent.com/assets/17548206/21184393/93bfb3ce-c20c-11e6-8003-f8071cb24719.jpeg)
![plotspecactivity](https://cloud.githubusercontent.com/assets/17548206/21184379/8bc719c8-c20c-11e6-8da9-c791fdc99463.jpeg)
![plotspecactivity1](https://cloud.githubusercontent.com/assets/17548206/21184383/8fe6731e-c20c-11e6-86f0-8c6a60de90bd.jpeg)

**Comment by jotech** [comment]
so I assume it is resolved, right?
