### ISSUE TITLE
PlotSubCurve cannot be run, when substances do not exist

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#26]
**Problem:**
I am encountering a problem with PlotSubCurve.
**Desciption and interpretation:**
PlotSubCurve cannot be run, because some substances cannot be found in exchange reactions (which is true; indeed some substances are not in the arena). For example, EX_pyr(e) belongs to metabolites_1 and only when I run  PlotSubCurve alone with it, I have data as output.

Please consider to allow PlotSubCurve to run independently from the existence of the compounds. 

My log :

**> CURVE<-plotSubCurve(simlist =sim,mediac = metabolites_1,ret_data = TRUE)**
_Error in plotSubCurve(simlist = sim, mediac = metabolites_1, ret_data = TRUE) : 
  Substance does not exist in exchange reactions.
In addition: Warning messages:
1: In .HTMLsearch(query) : Unrecognized search field: title
2: In .HTMLsearch(query) : Unrecognized search field: keyword
3: In .HTMLsearch(query) : Unrecognized search field: alias_
**> CURVE**
_Error: object 'CURVE' not found_
**> metabolites_1**
  _[1] "EX_but(e)"         "EX_ppa(e)"         "EX_ac(e)"          "EX_indole(e)"      "EX_ind3ac(e)"     
 ........I deleted the rest of the list......     .     
[76] "EX_isobut(e)"      "EX_isocapr(e)"     "EX_isoval(e)"      "EX_34hpp"          "EX_pyr(e)"
 ........I deleted the rest of the list......     
[141] "EX_urea(e)"        "EX_15dap(e)"       "EX_carn(e)"        "EX_crn(e)"_        
**> CURVE<-plotSubCurve(simlist =sim,mediac = "EX_pyr(e)",ret_data = TRUE)**
**> CURVE**
   _sub       time value replc
1  pyr 0.01666667     0     1
2  pyr 0.03333333     0     1
 ........I deleted the rest of the list......     
30 pyr 0.50000000     0     1
31 pyr 0.51666667     0     1_

**Comment by euba** [comment]
Hi, that's a very good point. I pushed a new code in which intersect of the given metabolites is taken with the metabolites in the arena. This will then not plot the metabolites in the arena. Also, you get an error if none of the metabolites you provided are in the arena.

**Comment by maringos** [comment]
I just updated my BacArena and now this new problem is appearing:

>  CURVE<-plotSubCurve(simlist = sim,mediac = metabolites_1,ret_data = TRUE)
> Error in simlist[[1]] : this S4 class is not subsettable

Something is not working well. Please revise accordingly. :)

**Comment by maringos** [comment]
Now it is working fine! Many thanks for the rapid solution!
