### ISSUE TITLE
Suggestion: simEnv output

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#27]
I would like to suggest one improvement to the BacArena:

- The simEnv generates a list of iterations together with other related information. This extensive output is (not) always useful, depending on the task somebody is working on.

- [ ] Please consider condensing it significantly or enabling an option of withholding such output.

- [ ] If there is such option, please inform me accordingly. 

Many Thanks in advance!

**Comment by jotech** [comment]
Thanks for pointing this out! 
Please use simEnv(arena, verbose=FALSE) to disable printing.
