### ISSUE TITLE
Secondary Objective

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#28]
I am encountering an error with regard to simEnv function. 
In a specific setting when I am using the mtf option

> sim   <- simEnv(sim, time=5, sec_obj = 'mtf')

this error appears and simulation stops

> Error: checkVersion(object) is not TRUE

Otherwise (without mtf) the R file with the simulation is running.

I can provide you with my script if you need it - It is huge; that is why I omit it.

**Comment by jotech** [comment]
Unfortunately without code it is almost impossible to answer.
Could you please try to provide a minimal example?

**Comment by maringos** [comment]
Please check the [log](https://github.com/euba/BacArena/files/648470/buggm.txt)
It is not minimal but representative...

**Comment by jotech** [comment]
Does the error occur without the human recon model?

**Comment by maringos** [comment]
Yes it does :)

**Comment by euba** [comment]
Hi, can you try `optimizeProb(sihumi[[1]])` If this gives you the same error, can you try ` optimizeProb(upgradeModelorg(sihumi[[1]]))`

**Comment by maringos** [comment]
When I am using this setting, I have this error immediately:
for(i in seq_along(sihumi)){
+   bac <-optimizeProb((sihumi[[i]]))
+   bac <- Bac(model=sihumi[[i]])
+   if (i==2) {
+     arena <- addOrg(arena, specI=bac, amount=2)}
+   else if (i==6) {
+     arena <- addOrg(arena, specI=bac, amount=2)}
+   else{
+     arena <- addOrg(arena, specI=bac, amount=5)
+   }
+ }
Error: checkVersion(object) is not TRUE

When I am using this setting, the same error appears but only at the beginning of the simulation:
for(i in seq_along(sihumi)){
+   bac <-optimizeProb(upgradeModelorg(sihumi[[i]]))
+   bac <- Bac(model=sihumi[[i]])
+   if (i==2) {
+     arena <- addOrg(arena, specI=bac, amount=2)}
+   else if (i==6) {
+     arena <- addOrg(arena, specI=bac, amount=2)}
+   else{
+     arena <- addOrg(arena, specI=bac, amount=5)
+   }
+ }

**Comment by jotech** [comment]
As Eugen wrote it is a problem with an old model file. Please upgrade it using ``upgradeModelorg``.

**Comment by euba** [comment]
Yes, this is because sybil changed their model structure in their new version. You can use this code
`for(i in 1:length(sihumi)){sihumi[[i]] <- upgradeModelorg(sihumi[[i]])}`
at the beginning of your simulation after loading sihumi2.RData, then you can save the new upgraded sihumi list.

**Comment by maringos** [comment]
It is working for me :) Many Thanks :)

**Comment by euba** [comment]
No problem :)
