### ISSUE TITLE
Suggestion: New Plot

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#31]
Dear All,

I would like to propose the creation of new plot for BacArena. There are substances that are involved in so many reactions, that noone can check them one by one. For that reason, I would like to have a function that has as input the substance (eg exchange reaction, or even intracellular compounds) and prints as output the most varying reactions in which the compound is used or produced.
Example:
In [VMH](http://vmh.uni.lu/#metabolite/accoa), the compound acetyl-CoA is involved in 245 human reactions. A plot (as proposed) for the most important (in terms of variation) reactions would improve dramatically the big-data-like problem "huge quantity of information, without meaningful information"

Regards,
GMaringos

**Comment by maringos** [comment]
To help you, I propose something like that:
```
bac = Bac(model=Ec_core, type="E. coli")
pattern="acetate"
model=bac@model
res_rea_<- grep(x=model@react_name, pattern=pattern, ignore.case = TRUE)
plotReaActivity(sim,reactions =as.list(print(paste(model@react_id[res_rea_]))))
```
Of course, you may have a better approach which I would really like to discuss with you.
P.S. The above code is 100% taken from the BacArena code and adapted accordingly (fair play).

**Comment by euba** [comment]
Hi, 

If you want the most varying metabolites you can try `getVarSubs()`. It will give you a vector of the metabolites, which are sorted according to their variation within the simulation.

`data("Ec_core")
bac <- Bac(Ec_core) #initialize a bacterium
arena <- Arena(n=20,m=20) #initialize the environment
arena <- addOrg(arena,bac,amount=10) #add 10 organisms
arena <- addSubs(arena,40) #add all possible substances
sim <- simEnv(arena,5)

most_varying_subs <- getVarSubs(sim)
top10 = head(most_varying_subs,10) #get the top 10 most varying substances
plotReaActivity(sim,names(top10))`

However, the function only outputs exchange reactions, so you wouldn't get the most changing internal reactions. But you could get the names of the metabolites and then figure out in which reactions they are involved in.

Best, Eugen

**Comment by maringos** [comment]
Many thanks for the answer; I will keep it mind for future use. My aim is to find the reactions in which the compounds involved in and specifically the internal ones, so that I can retrieve the "metabolic" information of the organism. For example, I can see massive production of hydrogen peroxide. Whose reactions is this result? For sure, I cannot search for 209 reactions. (I can but then it will take so much time)

**Comment by euba** [comment]
Ok, that sounds like an interesting idea. So you want to find the internal reactions that contribute to the concentration of a metabolite. I now created the function `findRxnFlux()` in my latest commit. This function basically takes the name of an exchange reaction and then looks in the stochiometric matrix which reactions are connected (produce/consume) the metabolite that the exchange reaction transports. Here is an example code (based on the sim object generated in the above comment) on how this works if you are interested:
```
ex= "EX_h(e)"
time = 5
reactind = which(model@react_id==ex) #find the index of the reaction
metind = which(model@S[,reactind]==-1) #find which metabolites this reaction is affecting
metcomp = gsub("\\[.\\]","",model@met_id) #strip off compartment id from metabolite
mets = which(metcomp %in% metcomp[metind]) #find which metabolites are there 
aff_rid = which(apply(abs(model@S[mets,]),2,sum)!=0) #get id of affected reactions
aff_rxn = model@react_id[aff_rid] #get the names of the afffected reactions

time=time+1
mtflux = sim@mfluxlist[[time]] #select right timestep from fluxlist
mtfmat = matrix(0,nrow=length(mtflux),ncol=length(aff_rxn),
                dimnames=list(names(sim@specs),aff_rxn)) #create matrix to store flux of each species
for(i in 1:length(mtflux)){ #iterate through each species
  mtfmat[i,aff_rxn] = mtflux[[i]][aff_rxn] #store flux of key reactions per species in matrix
}
sumflux = apply(abs(mtfmat),2,sum) #make the sum of the absolute flux for the reactions of each species
mtfmat[,names(sort(sumflux,decreasing=T))] #return the sorted matrix based on the absolute flux
```
If you want to use directly the function just type `fluxmat <- findRxnFlux(sim,"EX_h(e)",5)`. The output is a matrix with all fluxes for the associated reactions for each species. The matrix is sorted by the reactions with the highest fluxes, so if you don't want to go through everything you can sub-select the matrix (e.g. `fluxmat[,1:10]` for the ten most important reactions). Hope this helps (:

**Comment by maringos** [comment]
Season's Greetings!

What you proposed is really useful. Unfortunately, it is not included in the latest BacArena version, which I am using now.
```
> install_github(repo = "euba/BacArena")
Skipping install of 'BacArena' from a github remote, the SHA1 (3ce2458d) has not changed since last install.
  Use `force = TRUE` to force installation
> fluxmat <- findRxnFlux(sim,"EX_h(e)",5) #I used your example code
Error: could not find function "findRxnFlux"
```

**Comment by euba** [comment]
Hi, happy new year!

You are right, the commit was there, but I forgot to update the documentation. Now, `install_github()` should work with the new function.

**Comment by maringos** [comment]
Many Thanks. Now it seems ok. I am going to close the issue

**Comment by jotech** [comment]
I updated this very helpful function ``findRxnFlux``, please check 036eb72
