### ISSUE TITLE
Changing Row Order

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#33]
Let's assume a simplistic simulation. Why does each organism's row change from iteration to iteration in sim@simlist?

 ```
   sim@simlist

[[1]]
      growth type phenotype  x  y
1  0.4350093    1        NA 26  9
2  0.3066596    1        NA 28 49
3  0.4975020    1        NA 17 11
4  0.5025358    1        NA 20 27
5  0.6142047    1        NA 37 27
6  0.6349331    1        NA 43 44
7  0.5642620    1        NA 19 44
8  0.7617997    1        NA 21  3
9  0.4985623    1        NA 12 31
10 0.5744451    1        NA 22 16

[[2]]
      growth type phenotype  x  y
10 0.6271662    1         2 22 17
8  0.7603524    1         2 22  2
1  1.0105225    1         2 28 11
6  0.6740027    1         2 43 46
3  1.1246024    1         2 19 11
2  0.7517271    1         3 29 47
7  0.6189215    1         2 20 43
9  1.1264705    1         2 14 33
5  0.6583646    1         2 36 27
4  1.1334515    1         2 20 28
11 0.6271662    1        NA 23 16
12 0.7603524    1        NA 21  2
13 0.6740027    1        NA 44 44
14 0.6189215    1        NA 20 44
15 0.6583646    1        NA 38 28
```

It does not hurt anyone, but what is the meaning behind such mixing?

**Comment by jotech** [comment]
It's because the data.frame is shuffled each iteration to increase randomness (cf. [source code](https://github.com/euba/BacArena/blob/d541e29e3da985013a927a5ad1133d68d3a7f8ad/R/Arena.R#L742)).
Otherwise there could occur a bias for bacteria placed in the top of the data.frame because they always move and eat first. In BacArena, we chose [asynchronous updating](https://www.openabm.org/book/3138/updating-information).

**Comment by maringos** [comment]
I agree with the concept, but my point has another objective. Independently from what is going on the arena, printing the bacteria with a logical order( e.g. by weight or type etc) may help analysis, without disturbing the culture.

**Comment by jotech** [comment]
I would argue that it is an internal structure not directly used by the user. To sort it just to make it random again would only cost time. But what about using the rownames? Here, the order is preserved.

**Comment by maringos** [comment]
It is only a matter of elegance....

**Comment by jotech** [comment]
but in this case efficiency counts most ;)

**Comment by maringos** [comment]
That is why I have closed the thread....

**Comment by euba** [comment]
Hi, if you want to sort by growth or any other variable, you can also use this code:
```
library(BacArena)
sim = openArena()
sim@simlist[[1]][order(sim@simlist[[1]]$growth),]
```
or if you want to do it for the complete simlist:
```
for(i in seq_along(sim@simlist)){
  sim@simlist[[i]] = sim@simlist[[i]][order(sim@simlist[[i]]$growth),]
}
```
Instead of `$growth` you could also write another variable to sort for (e.g. `$type`).
I agree that we should keep the code as efficient as possible (-;
