### ISSUE TITLE
plotSubUsage-error

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#35]
```
plotShadowCost(sim) #it works
plotSubUsage(sim, 'EX_o2(e)') #it works
test<-c("EX_o2(e)", "blablabla(e)") #it works
plotSubUsage(sim, test) #it does not work
Error in plotSubUsage(sim, test) : Substance do not exist in arena
```

Why does the function not plot the oxygen usage?

**Comment by euba** [comment]
Hi, I like your exchange reaction "blablabla(e)". I updated the code to also output a plot if a exchange reaction is not in the medium.

**Comment by jotech** [comment]
So you also integrated a plot for blablabla(e) ;P ?

**Comment by euba** [comment]
No, we don't have a plot for blablabla(e) yet. This should be discussed in another issue ;-)
