### ISSUE TITLE
simlist[[1]] is not subsettable

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#38]
```
library(BacArena) #It does work
data(Ec_core) #It does work
arena<-Arena() #It does work
arena<-addOrg(object =arena,specI = Bac(Ec_core),amount = 5) #It does work
arena<-addDefaultMed(object = arena,org = Bac(Ec_core)) #It does work
sim<-simEnv(object = arena,time = 3,verbose = F) #It does work
plotSubUsage(simlist = sim) #It does not work


Error in simlist[[1]] : this S4 class is not subsettable
```

**Comment by euba** [comment]
Hi, the problem here is that you are using a function that expects a list, but you are giving it an "Eval" object. The point of having a list is that replicates of simulations are run and stored in a list. If you want to run it on one single object you can do `plotSubUsage(simlist = list(sim))`. I also modified the function accordingly.

**Comment by jotech** [comment]
For me the code is working without error! 
In [line](https://github.com/euba/BacArena/blob/5951a34baf31d5bf0622340ed512fd69706b08a8/R/Stuff.R#L683) eval is put in a list.

**Comment by maringos** [comment]
I updated my BacArena - now` plotSubUsage(simlist = sim)` is working again.

**Comment by euba** [comment]
@jotech You are right, the line to convert to a list was already there, I didn't see it before. The problem was just that before the first line already indexed simlist as a list and then the error was outputed in case it was not given as a Eval object.

**Comment by jotech** [comment]
@euba But there was no error for me trying the code above. I used the function many times before with eval objects.

**Comment by jotech** [comment]
okay now I see the problem was introduced by this commit: 5951a34baf31d5bf0622340ed512fd69706b08a8
Nonetheless, I would like to revert the messy one ca98ca854e920c118cdf9f699c9d51758d668544

**Comment by euba** [comment]
Ok, I reverted and updated. The code was messy because I used Atom as an editor and the default is to remove trailing blank spaces https://github.com/atom/whitespace/issues/10

**Comment by jotech** [comment]
thanks a lot!
