### ISSUE TITLE
Secondary Objectives

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#41]
Dear All,

My first point is that there is nowhere a list, where the options for secondary objectives are recorded. 

My second point, which is binded to the first one, there is no description for their function. What am I gaining or loosing by using them?

If there are these references, please inform me accordingly.

Regards,
[GMaringos](https://github.com/maringos)

**Comment by euba** [comment]
Hi, I added a little description for the secondary objective in the help of optimizeLP and simEnv.

**Comment by maringos** [comment]
Thanks! That is enough!
