### ISSUE TITLE
object@occupyM[n0:n, m0:m] : subscript out of bounds

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#47]
I think it is connected with the [commit 935a29f](https://github.com/euba/BacArena/commit/935a29f51aedd201dc69d3836e7f843502bb058e)
```
library(BacArena)
data(Ec_core, envir = environment())
bac = Bac(model=Ec_core, type="E. coli",lyse=T)
arena = Arena(n=34, m=112)
arena = addOrg(arena, bac,amount = 50)
```
**Error in object@occupyM[n0:n, m0:m] : subscript out of bounds**

**Comment by jotech** [comment]
should work now, please check and close if it is working.
