### ISSUE TITLE
AddOrg help is not clear enough

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#56]
The addOrg {BacArena} help function is not clear at least to me: Please explain and rephrase the following section if needed.
```
n0	
Start row of matrix to take free positions from (default 1)
n	
End column of matrix to take free positions from (default arena@m)
m0	
Start column of matrix to take free positions from (default 1)
m	
End row of matrix to take free positions from (default arena@n)
```

**Comment by jotech** [comment]
This is still mixed up with the row/column issue. I fixed the description.

**Comment by maringos** [comment]
Thanks. One question more: "Start row of matrix to take free positions from" means that the organism will be added in any position of the area that is starting from that point (without that point).

**Comment by jotech** [comment]
With this you can limit the area where orgs are positioned in case you do not specify coordinates with ``x`` and ``y``. And it is with that point not without.
