### ISSUE TITLE
Wrong cols and rows in plotSubDist

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#58]
Dear All,

I am suspecting the usual problem with the ncols and nrows in the function plotSubDist. Please check it thoroughly.

**Comment by euba** [comment]
Thanks for reporting. I fixed it accordingly in https://github.com/euba/BacArena/commit/6fba46223aeb10f0c62acb0ebd41c5822b07b7c9

**Comment by maringos** [comment]
Actually, is the correct way to report problems and propose a solution?

**Comment by jotech** [comment]
Interesting, thanks for pointing this out! You could also make a pull request than there is no need to copy and paste ;P
