### ISSUE TITLE
Misleading bug in Findfeeding3

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#59]
I am experiencing a bug in findfeeding3:
I have a list of substances to check for cross-feeding in the file
 flag<-read.csv(file = "~/hetero/metabolites_v2.csv",sep = ",",header = T)
flag$sub[94] is EX_pectintchol(e) which does not exist in sihumi_test.
flag$sub[75] is EX_ura(e) which does exist in sihumi_test.
The problems are two:
-The system invents a metabolite from nowhere : "134"
-The results are different depending on the type of the metabolites' list (character or factor)
My code with the response:
```
library(BacArena)
data("sihumi_test")
eval <- sihumi_test
flag<-read.csv(file = "~/hetero/metabolites_v2.csv",sep = ",",header = T)

findFeeding3(eval,time = 6,
 mets = c(as.character(flag$sub[94]),as.character(flag$sub[75])))

Error in findFeeding3(eval, time = 6, mets = c(as.character(flag$sub[94]),  : 
  No feeding found. Try other metaboites or time points.

findFeeding3(eval,time = 6,mets = c(flag$sub[94],(flag$sub[75])))
[[1]]
                 prod      cons met
1 B. thetaiotaomicron B. longum 134
2        L. plantarum B. longum 134

[[2]]
IGRAPH DN-- 3 2 -- 
+ attr: name (v/c)
+ edges (vertex names):
[1] B. thetaiotaomicron->B. longum L. plantarum       ->B. longum**

findFeeding3(eval,time = 6,mets = c(as.character(flag$sub[75])))
Error in findFeeding3(eval, time = 6, mets = c(as.character(flag$sub[75]))) : 
  No feeding found. Try other metaboites or time points.**

findFeeding3(eval,time = 6,mets = c(as.character(flag$sub[94])))
Error in findFeeding3(eval, time = 6, mets = c(as.character(flag$sub[94]))) : 
  No feeding found. Try other metaboites or time points.**

findFeeding3(eval,time = 6,mets = c((flag$sub[75])))
[[1]]
                 prod      cons met
1 B. thetaiotaomicron B. longum 134
2        L. plantarum B. longum 134

[[2]]
IGRAPH DN-- 3 2 -- 
+ attr: name (v/c)
+ edges (vertex names):
[1] B. thetaiotaomicron->B. longum L. plantarum       ->B. longum**

findFeeding3(eval,time = 6,mets = c(flag$sub[94]))
Error in findFeeding3(eval, time = 6, mets = c(flag$sub[94])) : 
  No feeding found. Try other metaboites or time points.**

```

**Comment by euba** [comment]
Hi, I cannot replicate your problem. When I try to put in a metabolite that is recognized `findFeeding3(eval,time = 6, mets = c("EX_ura(e)"))` I get the expected error `No feeding found. Try other metaboites or time points.`. So it is not possible to get an output if an metabolite is not recognized.

**Comment by maringos** [comment]
I rechecked the topic. Actually something strange takes places here:
```
is.factor(flag$sub[75])
[1] TRUE
is.integer(flag$sub[75])
[1] FALSE
typeof(flag$sub[75])
[1] "integer"
(flag$sub[75])
[1] EX_ura(e)
140 Levels: EX_10fthf(e) EX_10fthf5glu(e) EX_10fthf6glu(e) EX_10fthf7glu(e) EX_12ppd_S(e) ... EX_xoltri27(e)
```
I think this problem arose due to this inconsistency

**Comment by euba** [comment]
Ah ok, I see. You have to be careful with the `typeof` function, because it will give you the storage mode of the variable, not necessarily its class. In R factors are stored as integers
```
test =as.factor("test")
is.factor(test)
[1] TRUE
typeof(test)
[1] "integer"
```
You can use the `class` function instead to figure out the type of your variable
```
class(test)
[1] "factor"
```
I added a line in `findFeeding3` to convert mets into character and only take the mets which are in the environment.
