### ISSUE TITLE
Cell Duplication

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#63]
Dear All,

I cannot find the option in the Organism-class {BacArena} constructor which does not allow the cell to be duplicated.

Please inform me accordingly.

Regards
@maringos

**Comment by euba** [comment]
Hi, if you set the parameter `maxweight` in Organism to Infinity (`Inf`), the cell will not be able to duplicate.

**Comment by maringos** [comment]
Many thanks. That was my approach also :) So there is no such an option!
