### ISSUE TITLE
Diffusion Patterns

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#65]
Dear All,

I am wondering if the default diffusion patterns are realistic. My code is:
```
library(devtools)
#install_github(username="euba", repo="bacarena")
library(BacArena)
data(Ec_core, envir = environment())
bac2 = Bac(model=Ec_core, type="E. coli2",lyse=T)
arena = Arena(n=50, m=50)
arena = addOrg(arena, bac2, amount=50,n = 1)
arena = addDefaultMed(object = arena,org = bac2)
sim <- simEnv(arena, time=3,sec_obj = "mtf")  
evalArena(sim)
library(reshape2)
library(ggplot2)
plotSubDist2(sim,"EX_co2(e)")
plotSubDist(sim,"EX_co2(e)")

```
![rplot01](https://cloud.githubusercontent.com/assets/17548206/23519187/52b1ac6e-ff76-11e6-9475-82ae95dfbac2.jpeg)

![rplot](https://cloud.githubusercontent.com/assets/17548206/23519188/52b1e332-ff76-11e6-85f2-2c9e16191572.jpeg)

![rplot07](https://cloud.githubusercontent.com/assets/17548206/23519186/52b1b0f6-ff76-11e6-9619-f68df8d1db4a.jpeg)

**So does it take 3hrs just for diffusion to the half of the arena (0.00625 cm) ?**

**Comment by euba** [comment]
I think this is just an artifact of the plotting because in the upper plot of the concentration image you can see that the lowest concentration displayed is 625001 and the highest 625004 so the metabolite is actually almost uniformly distributed in the environment and does not stop at half of the arena.

**Comment by jotech** [comment]
I had a fresh look at the diffusion system and I'm now sure that the diffusion constant has to have the unit cm^2/h. So far we used cm^2/s which is not working correctly because tstep is in hours.

**Comment by jotech** [comment]
see 14fcfc18ba1513c75e3edb611c69ff7bf137e058

**Comment by maringos** [comment]
After installing new version and running the same code:
![1](https://user-images.githubusercontent.com/17548206/29623619-441334b8-8827-11e7-9b7e-23a0eb967e3c.jpeg)
![2](https://user-images.githubusercontent.com/17548206/29623620-44192c10-8827-11e7-9ade-b0e8ba993284.jpeg)

**Comment by jotech** [comment]
Numerics is responsible for this. Should be fine as discussed via mail.
