### ISSUE TITLE
EvalArena misleading argument

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#67]
The argument plot_items in EvalArena is misleading.
plot_items: A character vector giving the items, which should be plotted.

When I read it in the console (without looking the help), I think the question to plot or not to plot, but it is totally misleading. I suggest a new structure with these options:

input_items: A character vector giving the items, which should be plotted.
to_plot: To plot or not to plot the items
The last must be off at least when retdata is true.

**Comment by euba** [comment]
I think it is more difficult with two arguments because if you want to plot something you need to first specify the name of the item you want to plot and second if you want to plot it or not.
I added a more detailed description of what the argument does in the documentation.
