### ISSUE TITLE
Correct usage of units

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#68]
Dear All,

I am not sure that I have fully understood the functionality of the unit "mmol/Arena".

If a compound should be as much as 1mmol in a Arena, should I use the unit mmol or mmol/Arena?

In the real world when we say 1mmol in 1L, we mean add 1 mmol in a solution as large as 1L. In silico?

**Comment by maringos** [comment]
Update: I have checked the code and there is no such unit mmol. So if I have a value in mmol , should I just put it in Arena the compound as mmol/Arena?

**Comment by jotech** [comment]
Why not using mM when you want to have mmol/l ?
mmol/arena stands for the total amount in the arena. This means the the sum of all grid cells will be equal the defined value.

**Comment by maringos** [comment]
No, misunderstanding! My data is in mmol. 

The example with mM was only stated to make clear what one millimolar means in real life. The "/Arena" part of the unit confuses me: What I should add is mmol, not mmol/Arena, the program later transforms this value to mmol/Arena by dividing the value with the Arena dimensions.

From your answer I understand that if I have a value in mmol, I should use the unit mmol/Arena.
