### ISSUE TITLE
Possibly Misleading BacArena Vignette

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#69]
Page 7: Simulation with replicates

The `simlist <-parLapply(cl, 1:cores, function(i)` expression may be misleading. What I have understood is that the replicates have to be equal to the cores; whatever they have been set before, but @jotech explained my mistake. 

Please think about changing the `cores` parameter to a new one like `replicates` in the parLapply [@jotech].

Of course the whole issue is apparent for experienced users, but for newbies not.

**Comment by jotech** [comment]
interesting, thanks!
