### ISSUE TITLE
Combination of Findfeeding3

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#71]
Dear All,
Let's imagine a set of replications for a specific arena. I would like to ask you for implementation of a function like the Findfeeding3 but with the ability to combine and plot the feeding information (the fluxes between the cell models) for all replications. It sounds like the average or mean of these connections....
Regards,
@maringos

**Comment by euba** [comment]
Ok, I created a new function called `findFeeding3rep` for replicate simulations. It does the same as findFeeding but takes the mean of the flux values from different replicates. Additionally, there is also the argument `mfunction` which allows you to use something else than the mean such as the median.

@jotech I like the fact that findFeeding3 is used here. Next I hope plotCurves will be used over plotCurves2 (-;
