### ISSUE TITLE
Version 1.6

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#72]
I would like to ask you when you are going to make available this version in RCRAN.

**Comment by jotech** [comment]
as soon as possible. There is some review process before which could be tough.

**Comment by maringos** [comment]
But is it normal that the `install_github("euba/BacArena")` command does not give any update?

**Comment by jotech** [comment]
yes because you have already the latest version ;) 
version 1.6 is release for the current state of the art and will be used for the cran release

**Comment by maringos** [comment]
Thanks for the answer. Every release contains officially the latest version, which is anyway available from github. It is a matter of " nur zum Schein" ~ I like this concept.

**Comment by jotech** [comment]
it is necessary to be reproducible between cran and github releases

**Comment by maringos** [comment]
Ah ok  :+1:
