### ISSUE TITLE
Recognize shorter substance names

### ISSUE THREAD

**Issue by jotech** [euba/BacArena#74]
Substances IDs are named according to exchange reactions (something like ``EX_x(e)``). Quite a lot functions use substance IDs. It should be possible to use the shorter ID to address substances, i.e. ``x`` instead of  ``EX_x(e)``. This is already possible for some functions as getSubHist().

**Comment by maringos** [comment]
Ιs this issue correlated to the following commit https://github.com/euba/BacArena/commit/b283423758eabb9d26a92eae4c7d3f1e88c9c1a0 ?

**Comment by jotech** [comment]
As far as I can see no. The commit allows to use the name of a substance instead of the ID. The issue is about shorten the IDs. Maybe it is a general question how to name and handle substances.
