### ISSUE TITLE
findRxnFlux vs plotSpecActivity time concerns

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#75]
Dear All,
**My code:**
```
library(devtools)
#install_github(username="euba", repo="bacarena")
library(BacArena)
data(Ec_core, envir = environment())
bac1 = Bac(model=Ec_core, type="E. coli1",lyse=T)
bac2 = Bac(model=Ec_core, type="E. coli2",lyse=T)
arena = Arena(n=50, m=50)
arena = addOrg(arena, bac2, amount=50)
arena = addOrg(arena, bac1, amount=50)
arena = addDefaultMed(object = arena,org = bac2)
sim <- simEnv(arena, time=3,sec_obj = "mtf")  
```
**My situation:**
The function findRxnFlux gives this output and specifically concentrate on EX_h2o(e){L}  fluxes:
```
findRxnFlux(sim,ex = "EX_h2o(e)",time = 3)
Legend:	 {R} Substance is on the right site of the reaction definition (product)
	 {L} Substance is on the left site (educt) {T} possible transporter reactions

         ATPS4r{R} CYTBD{R} EX_h2o(e){L}   H2Ot{T}   ENO{R} ATPM{L}   PGL{L}  GLUDy{L}   PPC{L} ACONTa{R} ACONTb{L}    CS{L} Biomass_Ecoli_core_w_GAM{L}
E. coli2  4988.672 4577.365     3226.571 -3226.571 2206.762  939.68 903.5588 -577.4893 318.4186  218.0007  218.0007 218.0007                    111.1176
E. coli1  4604.185 4207.800     2975.538 -2975.538 2079.144  897.73 856.8589 -536.6967 295.9262  168.3504  168.3504 168.3504                    103.2685
           FUM{L}       MALS{L}
E. coli2 98.11591  2.866199e-15
E. coli1 56.93406 -2.402802e-15
```
The command` plotSpecActivity(sim,subs = "EX_h2o(e)")` plots this graph among others:
![rplot](https://cloud.githubusercontent.com/assets/17548206/24451771/6dd473f4-1480-11e7-9a8a-a271f2cf21e8.jpeg)

**My problem**
The time point 3 is inconsistent among these functions. Specifically the time point 3 of findRxnFlux seems to be the time point 4 of plotSpecActivity. Is that a bug? Have I understood correctly the situation?

Regards
@maringos

**Comment by euba** [comment]
Hi, this is because the time axis in plotSpecActivity starts with 1 and not with 0. This means that the initial condition is interpreted as time step 1.
I now changed it to start from 0 so that it is consistent with findRxnFlux.
