### ISSUE TITLE
What is the unit of plotSubDist2 plot?

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#76]
What is the unit of plotSubDist2 plotting result?

**Comment by maringos** [comment]
@jotech  said that it is fmol, but help shows "The generic function plotSubDist2 returns a plot for every time step which shows the substance **concentration** in the environment," What is the truth?

**Comment by maringos** [comment]
Any news?

**Comment by jotech** [comment]
fmol, if any further doubts just make a test arena with a defined input for one substance and without organisms and check the output of plotSubDist2.

**Comment by maringos** [comment]
Thanks. My objective was not to doubt @jotech 's expert opinion, but to clarify this topic. No offense.
