### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#80]
Dear All,

I am aware of the fact that your BacArena publication is going to be available soon. Do you have a DOI string ready to be cited?

Regards,
George

**Comment by jotech** [comment]
I would propose something like this:
E. Bauer*, J. Zimmermann*, F. Baldini, I. Thiele, C. Kaleta _“BacArena: Individual-Based Metabolic Modeling of Heterogeneous Microbes in Complex Communities”_, PLoS Computational Biology (2017) * These authors have contributed equally to this work.

You could also check: http://orbilu.uni.lu/handle/10993/30995

**Comment by maringos** [comment]
Thanks!
