### ISSUE TITLE
plotSubDist2_warning_times

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#82]
What is the meaning behind that?
-> plotSubDist2(sim,"EX_na1(u)")
Warning messages:
1: In max(times) : no non-missing arguments to max; returning -Inf
2: In min(times) : no non-missing arguments to min; returning Inf
Plot is generated.

**Comment by euba** [comment]
Hi, these are just warnings, that are generated if no time interval (simulation time steps) is given for the function. So this warning is not really informative.
I changed the function so that these warnings are avoided.
