### ISSUE TITLE
Bug in GLPK only?

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#85]
Dear All,

I am experiencing this FATAL error:
```
sim <- simEnv(arena, time=3)

iteration: 1 	 organisms: 20 	 biomass: 10.1763 pg 
                count  biomass %
XY          10 4.454483 0
XX    10 5.721821 0
Assertion failed: teta >= 0.0
Error detected in file simplex/spxchuzr.c at line 294
Aborted

```
A brief search on the web returns a problem in GLPK. Please check if the problem is of the BacArena software also.

Regards,
George

**Comment by euba** [comment]
Hi,

that's interesting. Could you also please give the code to generate the arena object?

Thanks, Eugen

**Comment by maringos** [comment]
Hi,

Actually this problem arises only when I load a specific model (@jotech C.Elegans model).

So something wrong is going on with this model and not with BacArena's software.

Many thanks,
George

**Comment by euba** [comment]
Ok, can you try to do a single FBA on the model itself: `optimizeProb(model)` 
It's a strange error, I have never seen it before.

**Comment by maringos** [comment]
Thanks for the hint. Well, the problem still exists. :)
```
> optimizeProb(X)
Loading required package: glpkAPI
using GLPK version 4.62
solver:                                   glpkAPI
method:                                   simplex
algorithm:                                fba
number of variables:                      1920
number of constraints:                    1642
return value of solver:                   solution process was successful
solution status:                          solution is optimal
value of objective function (fba):        49.703428
value of objective function (model):      49.703428

> optimizeProb(X, solver="lpSolveAPI")
Loading required package: lpSolveAPI
solver:                                   lpSolveAPI
method:                                   lp_solve
algorithm:                                fba
number of variables:                      1920
number of constraints:                    1642
return value of solver:                   optimal solution found
solution status:                          optimal solution found
value of objective function (fba):        49.703428
value of objective function (model):      49.703428
```

**Comment by euba** [comment]
Hmhmhm, so then the model solves normally. Maybe it is then a problem of the constraints you set in the Arena object. Did you try to set the medium concentration (also with all metabolites) really high and see if you get the same error? Does this error also occur with other solvers, e.g., lpSolveAPI and cplexAPI?

**Comment by maringos** [comment]
Ιn both cases it does not work. I found out that `X@medium` gives only this return
```
Beta-D-glucose 
   "EX_GLC(e)"
```
Then I searched in the model and it seems that it is somehow incompatible with the "normal" nomenclature. For example, the exchange reactions (except for glucose) are written like that....
```
> X@react_name[1886]
[1] "Glycogenin transport"

> X@react_id[1886]
[1] "Glycogenin_exchange(e)"
```
Thanks for the hints. They really helped me to understand what is going on.

**Comment by euba** [comment]
Ahhh, I see the problem now. If the nomenclature is different, he doesn't recognize the exchange reactions. What you need to do is to set the recognition of exchange reactions differently: `organism <- Bac(X, ex=NA)` or try `organism <- Bac(X, ex="_exchange")`
After doing this do `addOrg(arena, organism)` and check `X@medium` again to see if there are more exchange reactions detected.
Probably the error just tells you that you have a model that is unfeasible.

**Comment by maringos** [comment]
Perfect! Really nice support! After one year++ I am still learning BacArena hidden features!
