### ISSUE TITLE
BacArena::Bac-Constructor needs better documentation

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#86]
Dear All,

After solving the issue (https://github.com/euba/BacArena/issues/85), I have realised that the BacArena::Bac-Constructor needs better documentation. To be more exact, the arguments must provide also the link for the Organism-constructor. The link Organism-class does not provide all the arguments (e.g. ex).

Regards,
George

P.S. What about human-constructor?

**Comment by jotech** [comment]
I think it is necessary to distinguish between class variables and constructor parameters. 
``Ex`` for example is used by the constructor is not part of the organism object. That is why it is documented in the constructor but not in the organism class. When you try ``? organism`` you will see the help of the constructor which references also to the class help.

**Comment by maringos** [comment]
OK. I understand your argument. So I would suggest to add a footnote in the Bac-Constructor like... "For further arguments please check Organism-constructor check (link)". A user should not care about the internal structure of BacArena (I understand your strategy though), a user should only be able to find all argument together or with links (personal opinion).

**Comment by jotech** [comment]
i updated the reference which was set to organism-class. No it is linking to organism constructor where all parameters are explained.
