### ISSUE TITLE
findFeeding3: time=time+1

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#88]
Hello everybody,

I have realised that in the findFeeding3 code there is a line "time=time+1".  I try to understand how it works.

An example to make that clear, because for sure other people may have the same question:

I have chosen in the simEnv the argument: time=4.
seq_along(sim@mfluxlist) returns 1 2 3 4 5. I understand 1 is the time zero.
If I want to plot the interaction after 2h (complete 2h), which time is the best to choose in findfeeding3?

**Comment by euba** [comment]
Hi,

You right, the first element in the list is time point zero, so the just the arena that you gave as input without simulation. The time input you give in a function (for example findFeeding3) is actually the simulation time, so if you give 2h as input it will give you element 3 in the list. This is why we do "time=time+1".

Best, Eugen
