### ISSUE TITLE
Necessity: addOrgs by matrix

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#92]
I was wondering how useful would be to add bacteria by input of an occupyM-like matrix, where you specify which bacterium goes to which grid cell. (e.g. if x=1, y=2 in addorg, then I put the number 1 (the number of bacterium type) in the matrix position [2,1]).

If you think that is interesting, I can also think of developing it.....(unless you have already done it and I miss it; I think @jotech said that there is no such thing)

**Comment by jotech** [comment]
Thanks for pointing this out! The parameter ``x`` and ``y`` of ``addOrg`` can be vectors with coordinates. Using them, you could locate organisms on several places at once. Do you think this could also address your issue?

**Comment by maringos** [comment]
By using x and y is possible but painful to locate every each organism in case of a huge arena, which is a common setting . That is why I have proposed the function "addOrgbyMatrix": No need of repetitive addorg commands. You only need a spreadsheet as map, you save it and then you ask R to read it and transform it to matrix.

**Comment by jotech** [comment]
but you can provide all coordinates as x and y in one command, should even simpler then defining the matrix?

**Comment by maringos** [comment]
It is matter of perspective. Having something on a map is easier to see, to correct, to check, (even to color specific areas on the spreadsheet to help you; before saving of course) than to write the coordinates (even excessive typing can not be flawless), at least to my way of thinking. Anyway...you decide :)

**Comment by jotech** [comment]
If you think it is really needed we could integrate it but I would prefer to include it in addOrg itself because we have already a lot of overhead with functions.
By the way what about
```R
mat <- matrix(sample(c(0,1), 100, replace = TRUE), nrow = 10, ncol = 10)
which(mat==1, arr.ind=TRUE)
```
This will give you all indices of a matrix which could be used in addOrg

**Comment by maringos** [comment]
That is an another nice approach in comparison to melting the matrix. Thanks! I would like to point out that the whole topic is not what I really need (because I do not need an extra function for my personal use;  your solution or even my solution are fine), but what is best for BacArena software (for the future user). ;)

**Comment by jotech** [comment]
Common do not hide your concrete need behind a 'general user' ;)
I made a implementation for ``addOrg``. It worked for me, please have a try. Example is in ``?addOrg``

**Comment by maringos** [comment]
I do not hide anything. I am crystal clear. Since I do not characterize myself as developer but as user of BacArena and as potential developer, I always think about "How should we make it so simple that my grandmother (~90 years old) understands/uses that".....
As "developer" (if I accept it) I do not need anything. As "user" I do need such improvements.

**Comment by jotech** [comment]
yeah but don't you think that it's the same for me?? I would guess that people are doing things differently and that's what feature are used for. But let's discuss it and don't assume that somebody has higher standard because he or she is the user. We all are users and you are also a developer ;)
Anyway does it work for you?

**Comment by maringos** [comment]
No offense..that was/is my view. Should I open a new issue under the title "Politics of BacArena" ?  (I would love it) :) 
Let's return to the topic :)
Please check the cols and the rows of the matrix. They seem to me wrong (lines 172, 175, 176)
