### ISSUE TITLE
Sim should be replaced by object

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#97]
In Lines:
https://github.com/euba/BacArena/blob/303334b78e865363573eaa0ab78cb1f1cf83124c/R/Arena.R#L3081
https://github.com/euba/BacArena/blob/303334b78e865363573eaa0ab78cb1f1cf83124c/R/Arena.R#L3082
https://github.com/euba/BacArena/blob/303334b78e865363573eaa0ab78cb1f1cf83124c/R/Arena.R#L3094

The word sim should be replaced by the word object. I apologise for any inconvenience due to my mistake.

**Comment by jotech** [comment]
thanks for pointing it out! Do you want to make a pull request for this?

**Comment by maringos** [comment]
Thanks for the answer. Please check and approve my pull request.
