### ISSUE TITLE
Version of BacArena

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#99]
Hi,
It is not clear to me which version of BacArena I am currently using. For sure, I am using the development version. Could you help me how to identify it?

**Comment by jotech** [comment]
If you are using 
```R
library(devtools)
install_github("euba/bacarena")
```
to install Bacarena, then you will get the latest version available on github. The sha1 hash printed by ```install_github("euba/bacarena")``` (currently ```01d4eeb4```) is a direct link to the git commit [(01d4eeb4)](https://github.com/euba/BacArena/commit/01d4eeb440ddb9c30412fdc73625af1a3601119a)

**Comment by maringos** [comment]
OK! Only if I try updating it, I will find the commit code (let's name it version-like code). I think it is clear enough: I will close the issue.

**Comment by maringos** [comment]
Hi,
I found who to get the sha1 hash for BacArena
`packageDescription("BacArena")`
Regards,
Georgios
